// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/cpacredential"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/objects"
)

// CPACredentialUpdate is the builder for updating CPACredential entities.
type CPACredentialUpdate struct {
	config
	hooks     []Hook
	mutation  *CPACredentialMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CPACredentialUpdate builder.
func (_u *CPACredentialUpdate) Where(ps ...predicate.CPACredential) *CPACredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CPACredentialUpdate) SetUpdatedAt(v time.Time) *CPACredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalKey sets the "external_key" field.
func (_u *CPACredentialUpdate) SetExternalKey(v string) *CPACredentialUpdate {
	_u.mutation.SetExternalKey(v)
	return _u
}

// SetNillableExternalKey sets the "external_key" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableExternalKey(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetExternalKey(*v)
	}
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *CPACredentialUpdate) SetAuthIndex(v string) *CPACredentialUpdate {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableAuthIndex(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetRemoteName sets the "remote_name" field.
func (_u *CPACredentialUpdate) SetRemoteName(v string) *CPACredentialUpdate {
	_u.mutation.SetRemoteName(v)
	return _u
}

// SetNillableRemoteName sets the "remote_name" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableRemoteName(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetRemoteName(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *CPACredentialUpdate) SetLabel(v string) *CPACredentialUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableLabel(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *CPACredentialUpdate) SetDisplayName(v string) *CPACredentialUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableDisplayName(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDisplayNameSortKey sets the "display_name_sort_key" field.
func (_u *CPACredentialUpdate) SetDisplayNameSortKey(v string) *CPACredentialUpdate {
	_u.mutation.SetDisplayNameSortKey(v)
	return _u
}

// SetNillableDisplayNameSortKey sets the "display_name_sort_key" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableDisplayNameSortKey(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetDisplayNameSortKey(*v)
	}
	return _u
}

// SetDisplayNameSortLength sets the "display_name_sort_length" field.
func (_u *CPACredentialUpdate) SetDisplayNameSortLength(v int) *CPACredentialUpdate {
	_u.mutation.ResetDisplayNameSortLength()
	_u.mutation.SetDisplayNameSortLength(v)
	return _u
}

// SetNillableDisplayNameSortLength sets the "display_name_sort_length" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableDisplayNameSortLength(v *int) *CPACredentialUpdate {
	if v != nil {
		_u.SetDisplayNameSortLength(*v)
	}
	return _u
}

// AddDisplayNameSortLength adds value to the "display_name_sort_length" field.
func (_u *CPACredentialUpdate) AddDisplayNameSortLength(v int) *CPACredentialUpdate {
	_u.mutation.AddDisplayNameSortLength(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CPACredentialUpdate) SetProvider(v string) *CPACredentialUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableProvider(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CPACredentialUpdate) SetEmail(v string) *CPACredentialUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableEmail(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CPACredentialUpdate) SetStatus(v string) *CPACredentialUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableStatus(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusMessage sets the "status_message" field.
func (_u *CPACredentialUpdate) SetStatusMessage(v string) *CPACredentialUpdate {
	_u.mutation.SetStatusMessage(v)
	return _u
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableStatusMessage(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetStatusMessage(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *CPACredentialUpdate) SetDisabled(v bool) *CPACredentialUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableDisabled(v *bool) *CPACredentialUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUnavailable sets the "unavailable" field.
func (_u *CPACredentialUpdate) SetUnavailable(v bool) *CPACredentialUpdate {
	_u.mutation.SetUnavailable(v)
	return _u
}

// SetNillableUnavailable sets the "unavailable" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableUnavailable(v *bool) *CPACredentialUpdate {
	if v != nil {
		_u.SetUnavailable(*v)
	}
	return _u
}

// SetRuntimeOnly sets the "runtime_only" field.
func (_u *CPACredentialUpdate) SetRuntimeOnly(v bool) *CPACredentialUpdate {
	_u.mutation.SetRuntimeOnly(v)
	return _u
}

// SetNillableRuntimeOnly sets the "runtime_only" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableRuntimeOnly(v *bool) *CPACredentialUpdate {
	if v != nil {
		_u.SetRuntimeOnly(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CPACredentialUpdate) SetPriority(v int) *CPACredentialUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillablePriority(v *int) *CPACredentialUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CPACredentialUpdate) AddPriority(v int) *CPACredentialUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetPlanType sets the "plan_type" field.
func (_u *CPACredentialUpdate) SetPlanType(v string) *CPACredentialUpdate {
	_u.mutation.SetPlanType(v)
	return _u
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillablePlanType(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetPlanType(*v)
	}
	return _u
}

// SetQuotaContext sets the "quota_context" field.
func (_u *CPACredentialUpdate) SetQuotaContext(v objects.CPAQuotaContext) *CPACredentialUpdate {
	_u.mutation.SetQuotaContext(v)
	return _u
}

// SetNillableQuotaContext sets the "quota_context" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaContext(v *objects.CPAQuotaContext) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaContext(*v)
	}
	return _u
}

// SetQuotaState sets the "quota_state" field.
func (_u *CPACredentialUpdate) SetQuotaState(v string) *CPACredentialUpdate {
	_u.mutation.SetQuotaState(v)
	return _u
}

// SetNillableQuotaState sets the "quota_state" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaState(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaState(*v)
	}
	return _u
}

// SetHealthState sets the "health_state" field.
func (_u *CPACredentialUpdate) SetHealthState(v string) *CPACredentialUpdate {
	_u.mutation.SetHealthState(v)
	return _u
}

// SetNillableHealthState sets the "health_state" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableHealthState(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetHealthState(*v)
	}
	return _u
}

// SetQuotaCooling sets the "quota_cooling" field.
func (_u *CPACredentialUpdate) SetQuotaCooling(v bool) *CPACredentialUpdate {
	_u.mutation.SetQuotaCooling(v)
	return _u
}

// SetNillableQuotaCooling sets the "quota_cooling" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaCooling(v *bool) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaCooling(*v)
	}
	return _u
}

// SetQuotaCooldownUntil sets the "quota_cooldown_until" field.
func (_u *CPACredentialUpdate) SetQuotaCooldownUntil(v time.Time) *CPACredentialUpdate {
	_u.mutation.SetQuotaCooldownUntil(v)
	return _u
}

// SetNillableQuotaCooldownUntil sets the "quota_cooldown_until" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaCooldownUntil(v *time.Time) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaCooldownUntil(*v)
	}
	return _u
}

// ClearQuotaCooldownUntil clears the value of the "quota_cooldown_until" field.
func (_u *CPACredentialUpdate) ClearQuotaCooldownUntil() *CPACredentialUpdate {
	_u.mutation.ClearQuotaCooldownUntil()
	return _u
}

// SetProjectionVersion sets the "projection_version" field.
func (_u *CPACredentialUpdate) SetProjectionVersion(v int) *CPACredentialUpdate {
	_u.mutation.ResetProjectionVersion()
	_u.mutation.SetProjectionVersion(v)
	return _u
}

// SetNillableProjectionVersion sets the "projection_version" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableProjectionVersion(v *int) *CPACredentialUpdate {
	if v != nil {
		_u.SetProjectionVersion(*v)
	}
	return _u
}

// AddProjectionVersion adds value to the "projection_version" field.
func (_u *CPACredentialUpdate) AddProjectionVersion(v int) *CPACredentialUpdate {
	_u.mutation.AddProjectionVersion(v)
	return _u
}

// SetQuotaData sets the "quota_data" field.
func (_u *CPACredentialUpdate) SetQuotaData(v objects.CPAQuotaSnapshot) *CPACredentialUpdate {
	_u.mutation.SetQuotaData(v)
	return _u
}

// SetNillableQuotaData sets the "quota_data" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaData(v *objects.CPAQuotaSnapshot) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaData(*v)
	}
	return _u
}

// SetQuotaLastAttemptAt sets the "quota_last_attempt_at" field.
func (_u *CPACredentialUpdate) SetQuotaLastAttemptAt(v time.Time) *CPACredentialUpdate {
	_u.mutation.SetQuotaLastAttemptAt(v)
	return _u
}

// SetNillableQuotaLastAttemptAt sets the "quota_last_attempt_at" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaLastAttemptAt(v *time.Time) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaLastAttemptAt(*v)
	}
	return _u
}

// ClearQuotaLastAttemptAt clears the value of the "quota_last_attempt_at" field.
func (_u *CPACredentialUpdate) ClearQuotaLastAttemptAt() *CPACredentialUpdate {
	_u.mutation.ClearQuotaLastAttemptAt()
	return _u
}

// SetQuotaLastSuccessAt sets the "quota_last_success_at" field.
func (_u *CPACredentialUpdate) SetQuotaLastSuccessAt(v time.Time) *CPACredentialUpdate {
	_u.mutation.SetQuotaLastSuccessAt(v)
	return _u
}

// SetNillableQuotaLastSuccessAt sets the "quota_last_success_at" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaLastSuccessAt(v *time.Time) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaLastSuccessAt(*v)
	}
	return _u
}

// ClearQuotaLastSuccessAt clears the value of the "quota_last_success_at" field.
func (_u *CPACredentialUpdate) ClearQuotaLastSuccessAt() *CPACredentialUpdate {
	_u.mutation.ClearQuotaLastSuccessAt()
	return _u
}

// SetQuotaLastFailureAt sets the "quota_last_failure_at" field.
func (_u *CPACredentialUpdate) SetQuotaLastFailureAt(v time.Time) *CPACredentialUpdate {
	_u.mutation.SetQuotaLastFailureAt(v)
	return _u
}

// SetNillableQuotaLastFailureAt sets the "quota_last_failure_at" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaLastFailureAt(v *time.Time) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaLastFailureAt(*v)
	}
	return _u
}

// ClearQuotaLastFailureAt clears the value of the "quota_last_failure_at" field.
func (_u *CPACredentialUpdate) ClearQuotaLastFailureAt() *CPACredentialUpdate {
	_u.mutation.ClearQuotaLastFailureAt()
	return _u
}

// SetQuotaLastError sets the "quota_last_error" field.
func (_u *CPACredentialUpdate) SetQuotaLastError(v string) *CPACredentialUpdate {
	_u.mutation.SetQuotaLastError(v)
	return _u
}

// SetNillableQuotaLastError sets the "quota_last_error" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaLastError(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaLastError(*v)
	}
	return _u
}

// SetRefreshLeaseToken sets the "refresh_lease_token" field.
func (_u *CPACredentialUpdate) SetRefreshLeaseToken(v string) *CPACredentialUpdate {
	_u.mutation.SetRefreshLeaseToken(v)
	return _u
}

// SetNillableRefreshLeaseToken sets the "refresh_lease_token" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableRefreshLeaseToken(v *string) *CPACredentialUpdate {
	if v != nil {
		_u.SetRefreshLeaseToken(*v)
	}
	return _u
}

// SetRefreshLeaseUntil sets the "refresh_lease_until" field.
func (_u *CPACredentialUpdate) SetRefreshLeaseUntil(v time.Time) *CPACredentialUpdate {
	_u.mutation.SetRefreshLeaseUntil(v)
	return _u
}

// SetNillableRefreshLeaseUntil sets the "refresh_lease_until" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableRefreshLeaseUntil(v *time.Time) *CPACredentialUpdate {
	if v != nil {
		_u.SetRefreshLeaseUntil(*v)
	}
	return _u
}

// ClearRefreshLeaseUntil clears the value of the "refresh_lease_until" field.
func (_u *CPACredentialUpdate) ClearRefreshLeaseUntil() *CPACredentialUpdate {
	_u.mutation.ClearRefreshLeaseUntil()
	return _u
}

// SetRefreshRevision sets the "refresh_revision" field.
func (_u *CPACredentialUpdate) SetRefreshRevision(v int) *CPACredentialUpdate {
	_u.mutation.ResetRefreshRevision()
	_u.mutation.SetRefreshRevision(v)
	return _u
}

// SetNillableRefreshRevision sets the "refresh_revision" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableRefreshRevision(v *int) *CPACredentialUpdate {
	if v != nil {
		_u.SetRefreshRevision(*v)
	}
	return _u
}

// AddRefreshRevision adds value to the "refresh_revision" field.
func (_u *CPACredentialUpdate) AddRefreshRevision(v int) *CPACredentialUpdate {
	_u.mutation.AddRefreshRevision(v)
	return _u
}

// SetQuotaObserved sets the "quota_observed" field.
func (_u *CPACredentialUpdate) SetQuotaObserved(v objects.CPAQuotaObserved) *CPACredentialUpdate {
	_u.mutation.SetQuotaObserved(v)
	return _u
}

// SetNillableQuotaObserved sets the "quota_observed" field if the given value is not nil.
func (_u *CPACredentialUpdate) SetNillableQuotaObserved(v *objects.CPAQuotaObserved) *CPACredentialUpdate {
	if v != nil {
		_u.SetQuotaObserved(*v)
	}
	return _u
}

// ClearQuotaObserved clears the value of the "quota_observed" field.
func (_u *CPACredentialUpdate) ClearQuotaObserved() *CPACredentialUpdate {
	_u.mutation.ClearQuotaObserved()
	return _u
}

// Mutation returns the CPACredentialMutation object of the builder.
func (_u *CPACredentialUpdate) Mutation() *CPACredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CPACredentialUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CPACredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CPACredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CPACredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CPACredentialUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if cpacredential.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpacredential.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cpacredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CPACredentialUpdate) check() error {
	if v, ok := _u.mutation.ExternalKey(); ok {
		if err := cpacredential.ExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "external_key", err: fmt.Errorf(`ent: validator failed for field "CPACredential.external_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemoteName(); ok {
		if err := cpacredential.RemoteNameValidator(v); err != nil {
			return &ValidationError{Name: "remote_name", err: fmt.Errorf(`ent: validator failed for field "CPACredential.remote_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := cpacredential.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "CPACredential.display_name": %w`, err)}
		}
	}
	if _u.mutation.CpaInstanceCleared() && len(_u.mutation.CpaInstanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CPACredential.cpa_instance"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CPACredentialUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CPACredentialUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CPACredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cpacredential.Table, cpacredential.Columns, sqlgraph.NewFieldSpec(cpacredential.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cpacredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalKey(); ok {
		_spec.SetField(cpacredential.FieldExternalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(cpacredential.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteName(); ok {
		_spec.SetField(cpacredential.FieldRemoteName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(cpacredential.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(cpacredential.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameSortKey(); ok {
		_spec.SetField(cpacredential.FieldDisplayNameSortKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameSortLength(); ok {
		_spec.SetField(cpacredential.FieldDisplayNameSortLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayNameSortLength(); ok {
		_spec.AddField(cpacredential.FieldDisplayNameSortLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(cpacredential.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(cpacredential.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cpacredential.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusMessage(); ok {
		_spec.SetField(cpacredential.FieldStatusMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(cpacredential.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Unavailable(); ok {
		_spec.SetField(cpacredential.FieldUnavailable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RuntimeOnly(); ok {
		_spec.SetField(cpacredential.FieldRuntimeOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(cpacredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(cpacredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanType(); ok {
		_spec.SetField(cpacredential.FieldPlanType, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaContext(); ok {
		_spec.SetField(cpacredential.FieldQuotaContext, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.QuotaState(); ok {
		_spec.SetField(cpacredential.FieldQuotaState, field.TypeString, value)
	}
	if value, ok := _u.mutation.HealthState(); ok {
		_spec.SetField(cpacredential.FieldHealthState, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaCooling(); ok {
		_spec.SetField(cpacredential.FieldQuotaCooling, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuotaCooldownUntil(); ok {
		_spec.SetField(cpacredential.FieldQuotaCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.QuotaCooldownUntilCleared() {
		_spec.ClearField(cpacredential.FieldQuotaCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ProjectionVersion(); ok {
		_spec.SetField(cpacredential.FieldProjectionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProjectionVersion(); ok {
		_spec.AddField(cpacredential.FieldProjectionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaData(); ok {
		_spec.SetField(cpacredential.FieldQuotaData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.QuotaLastAttemptAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.QuotaLastAttemptAtCleared() {
		_spec.ClearField(cpacredential.FieldQuotaLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QuotaLastSuccessAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.QuotaLastSuccessAtCleared() {
		_spec.ClearField(cpacredential.FieldQuotaLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QuotaLastFailureAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastFailureAt, field.TypeTime, value)
	}
	if _u.mutation.QuotaLastFailureAtCleared() {
		_spec.ClearField(cpacredential.FieldQuotaLastFailureAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QuotaLastError(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshLeaseToken(); ok {
		_spec.SetField(cpacredential.FieldRefreshLeaseToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshLeaseUntil(); ok {
		_spec.SetField(cpacredential.FieldRefreshLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.RefreshLeaseUntilCleared() {
		_spec.ClearField(cpacredential.FieldRefreshLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.RefreshRevision(); ok {
		_spec.SetField(cpacredential.FieldRefreshRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshRevision(); ok {
		_spec.AddField(cpacredential.FieldRefreshRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaObserved(); ok {
		_spec.SetField(cpacredential.FieldQuotaObserved, field.TypeJSON, value)
	}
	if _u.mutation.QuotaObservedCleared() {
		_spec.ClearField(cpacredential.FieldQuotaObserved, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cpacredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CPACredentialUpdateOne is the builder for updating a single CPACredential entity.
type CPACredentialUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CPACredentialMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CPACredentialUpdateOne) SetUpdatedAt(v time.Time) *CPACredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalKey sets the "external_key" field.
func (_u *CPACredentialUpdateOne) SetExternalKey(v string) *CPACredentialUpdateOne {
	_u.mutation.SetExternalKey(v)
	return _u
}

// SetNillableExternalKey sets the "external_key" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableExternalKey(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetExternalKey(*v)
	}
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *CPACredentialUpdateOne) SetAuthIndex(v string) *CPACredentialUpdateOne {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableAuthIndex(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetRemoteName sets the "remote_name" field.
func (_u *CPACredentialUpdateOne) SetRemoteName(v string) *CPACredentialUpdateOne {
	_u.mutation.SetRemoteName(v)
	return _u
}

// SetNillableRemoteName sets the "remote_name" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableRemoteName(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetRemoteName(*v)
	}
	return _u
}

// SetLabel sets the "label" field.
func (_u *CPACredentialUpdateOne) SetLabel(v string) *CPACredentialUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableLabel(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *CPACredentialUpdateOne) SetDisplayName(v string) *CPACredentialUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableDisplayName(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetDisplayNameSortKey sets the "display_name_sort_key" field.
func (_u *CPACredentialUpdateOne) SetDisplayNameSortKey(v string) *CPACredentialUpdateOne {
	_u.mutation.SetDisplayNameSortKey(v)
	return _u
}

// SetNillableDisplayNameSortKey sets the "display_name_sort_key" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableDisplayNameSortKey(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetDisplayNameSortKey(*v)
	}
	return _u
}

// SetDisplayNameSortLength sets the "display_name_sort_length" field.
func (_u *CPACredentialUpdateOne) SetDisplayNameSortLength(v int) *CPACredentialUpdateOne {
	_u.mutation.ResetDisplayNameSortLength()
	_u.mutation.SetDisplayNameSortLength(v)
	return _u
}

// SetNillableDisplayNameSortLength sets the "display_name_sort_length" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableDisplayNameSortLength(v *int) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetDisplayNameSortLength(*v)
	}
	return _u
}

// AddDisplayNameSortLength adds value to the "display_name_sort_length" field.
func (_u *CPACredentialUpdateOne) AddDisplayNameSortLength(v int) *CPACredentialUpdateOne {
	_u.mutation.AddDisplayNameSortLength(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CPACredentialUpdateOne) SetProvider(v string) *CPACredentialUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableProvider(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *CPACredentialUpdateOne) SetEmail(v string) *CPACredentialUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableEmail(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CPACredentialUpdateOne) SetStatus(v string) *CPACredentialUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableStatus(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusMessage sets the "status_message" field.
func (_u *CPACredentialUpdateOne) SetStatusMessage(v string) *CPACredentialUpdateOne {
	_u.mutation.SetStatusMessage(v)
	return _u
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableStatusMessage(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetStatusMessage(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *CPACredentialUpdateOne) SetDisabled(v bool) *CPACredentialUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableDisabled(v *bool) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUnavailable sets the "unavailable" field.
func (_u *CPACredentialUpdateOne) SetUnavailable(v bool) *CPACredentialUpdateOne {
	_u.mutation.SetUnavailable(v)
	return _u
}

// SetNillableUnavailable sets the "unavailable" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableUnavailable(v *bool) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetUnavailable(*v)
	}
	return _u
}

// SetRuntimeOnly sets the "runtime_only" field.
func (_u *CPACredentialUpdateOne) SetRuntimeOnly(v bool) *CPACredentialUpdateOne {
	_u.mutation.SetRuntimeOnly(v)
	return _u
}

// SetNillableRuntimeOnly sets the "runtime_only" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableRuntimeOnly(v *bool) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetRuntimeOnly(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CPACredentialUpdateOne) SetPriority(v int) *CPACredentialUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillablePriority(v *int) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CPACredentialUpdateOne) AddPriority(v int) *CPACredentialUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetPlanType sets the "plan_type" field.
func (_u *CPACredentialUpdateOne) SetPlanType(v string) *CPACredentialUpdateOne {
	_u.mutation.SetPlanType(v)
	return _u
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillablePlanType(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetPlanType(*v)
	}
	return _u
}

// SetQuotaContext sets the "quota_context" field.
func (_u *CPACredentialUpdateOne) SetQuotaContext(v objects.CPAQuotaContext) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaContext(v)
	return _u
}

// SetNillableQuotaContext sets the "quota_context" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaContext(v *objects.CPAQuotaContext) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaContext(*v)
	}
	return _u
}

// SetQuotaState sets the "quota_state" field.
func (_u *CPACredentialUpdateOne) SetQuotaState(v string) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaState(v)
	return _u
}

// SetNillableQuotaState sets the "quota_state" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaState(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaState(*v)
	}
	return _u
}

// SetHealthState sets the "health_state" field.
func (_u *CPACredentialUpdateOne) SetHealthState(v string) *CPACredentialUpdateOne {
	_u.mutation.SetHealthState(v)
	return _u
}

// SetNillableHealthState sets the "health_state" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableHealthState(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetHealthState(*v)
	}
	return _u
}

// SetQuotaCooling sets the "quota_cooling" field.
func (_u *CPACredentialUpdateOne) SetQuotaCooling(v bool) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaCooling(v)
	return _u
}

// SetNillableQuotaCooling sets the "quota_cooling" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaCooling(v *bool) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaCooling(*v)
	}
	return _u
}

// SetQuotaCooldownUntil sets the "quota_cooldown_until" field.
func (_u *CPACredentialUpdateOne) SetQuotaCooldownUntil(v time.Time) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaCooldownUntil(v)
	return _u
}

// SetNillableQuotaCooldownUntil sets the "quota_cooldown_until" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaCooldownUntil(v *time.Time) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaCooldownUntil(*v)
	}
	return _u
}

// ClearQuotaCooldownUntil clears the value of the "quota_cooldown_until" field.
func (_u *CPACredentialUpdateOne) ClearQuotaCooldownUntil() *CPACredentialUpdateOne {
	_u.mutation.ClearQuotaCooldownUntil()
	return _u
}

// SetProjectionVersion sets the "projection_version" field.
func (_u *CPACredentialUpdateOne) SetProjectionVersion(v int) *CPACredentialUpdateOne {
	_u.mutation.ResetProjectionVersion()
	_u.mutation.SetProjectionVersion(v)
	return _u
}

// SetNillableProjectionVersion sets the "projection_version" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableProjectionVersion(v *int) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetProjectionVersion(*v)
	}
	return _u
}

// AddProjectionVersion adds value to the "projection_version" field.
func (_u *CPACredentialUpdateOne) AddProjectionVersion(v int) *CPACredentialUpdateOne {
	_u.mutation.AddProjectionVersion(v)
	return _u
}

// SetQuotaData sets the "quota_data" field.
func (_u *CPACredentialUpdateOne) SetQuotaData(v objects.CPAQuotaSnapshot) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaData(v)
	return _u
}

// SetNillableQuotaData sets the "quota_data" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaData(v *objects.CPAQuotaSnapshot) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaData(*v)
	}
	return _u
}

// SetQuotaLastAttemptAt sets the "quota_last_attempt_at" field.
func (_u *CPACredentialUpdateOne) SetQuotaLastAttemptAt(v time.Time) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaLastAttemptAt(v)
	return _u
}

// SetNillableQuotaLastAttemptAt sets the "quota_last_attempt_at" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaLastAttemptAt(v *time.Time) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaLastAttemptAt(*v)
	}
	return _u
}

// ClearQuotaLastAttemptAt clears the value of the "quota_last_attempt_at" field.
func (_u *CPACredentialUpdateOne) ClearQuotaLastAttemptAt() *CPACredentialUpdateOne {
	_u.mutation.ClearQuotaLastAttemptAt()
	return _u
}

// SetQuotaLastSuccessAt sets the "quota_last_success_at" field.
func (_u *CPACredentialUpdateOne) SetQuotaLastSuccessAt(v time.Time) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaLastSuccessAt(v)
	return _u
}

// SetNillableQuotaLastSuccessAt sets the "quota_last_success_at" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaLastSuccessAt(v *time.Time) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaLastSuccessAt(*v)
	}
	return _u
}

// ClearQuotaLastSuccessAt clears the value of the "quota_last_success_at" field.
func (_u *CPACredentialUpdateOne) ClearQuotaLastSuccessAt() *CPACredentialUpdateOne {
	_u.mutation.ClearQuotaLastSuccessAt()
	return _u
}

// SetQuotaLastFailureAt sets the "quota_last_failure_at" field.
func (_u *CPACredentialUpdateOne) SetQuotaLastFailureAt(v time.Time) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaLastFailureAt(v)
	return _u
}

// SetNillableQuotaLastFailureAt sets the "quota_last_failure_at" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaLastFailureAt(v *time.Time) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaLastFailureAt(*v)
	}
	return _u
}

// ClearQuotaLastFailureAt clears the value of the "quota_last_failure_at" field.
func (_u *CPACredentialUpdateOne) ClearQuotaLastFailureAt() *CPACredentialUpdateOne {
	_u.mutation.ClearQuotaLastFailureAt()
	return _u
}

// SetQuotaLastError sets the "quota_last_error" field.
func (_u *CPACredentialUpdateOne) SetQuotaLastError(v string) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaLastError(v)
	return _u
}

// SetNillableQuotaLastError sets the "quota_last_error" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaLastError(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaLastError(*v)
	}
	return _u
}

// SetRefreshLeaseToken sets the "refresh_lease_token" field.
func (_u *CPACredentialUpdateOne) SetRefreshLeaseToken(v string) *CPACredentialUpdateOne {
	_u.mutation.SetRefreshLeaseToken(v)
	return _u
}

// SetNillableRefreshLeaseToken sets the "refresh_lease_token" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableRefreshLeaseToken(v *string) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetRefreshLeaseToken(*v)
	}
	return _u
}

// SetRefreshLeaseUntil sets the "refresh_lease_until" field.
func (_u *CPACredentialUpdateOne) SetRefreshLeaseUntil(v time.Time) *CPACredentialUpdateOne {
	_u.mutation.SetRefreshLeaseUntil(v)
	return _u
}

// SetNillableRefreshLeaseUntil sets the "refresh_lease_until" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableRefreshLeaseUntil(v *time.Time) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetRefreshLeaseUntil(*v)
	}
	return _u
}

// ClearRefreshLeaseUntil clears the value of the "refresh_lease_until" field.
func (_u *CPACredentialUpdateOne) ClearRefreshLeaseUntil() *CPACredentialUpdateOne {
	_u.mutation.ClearRefreshLeaseUntil()
	return _u
}

// SetRefreshRevision sets the "refresh_revision" field.
func (_u *CPACredentialUpdateOne) SetRefreshRevision(v int) *CPACredentialUpdateOne {
	_u.mutation.ResetRefreshRevision()
	_u.mutation.SetRefreshRevision(v)
	return _u
}

// SetNillableRefreshRevision sets the "refresh_revision" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableRefreshRevision(v *int) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetRefreshRevision(*v)
	}
	return _u
}

// AddRefreshRevision adds value to the "refresh_revision" field.
func (_u *CPACredentialUpdateOne) AddRefreshRevision(v int) *CPACredentialUpdateOne {
	_u.mutation.AddRefreshRevision(v)
	return _u
}

// SetQuotaObserved sets the "quota_observed" field.
func (_u *CPACredentialUpdateOne) SetQuotaObserved(v objects.CPAQuotaObserved) *CPACredentialUpdateOne {
	_u.mutation.SetQuotaObserved(v)
	return _u
}

// SetNillableQuotaObserved sets the "quota_observed" field if the given value is not nil.
func (_u *CPACredentialUpdateOne) SetNillableQuotaObserved(v *objects.CPAQuotaObserved) *CPACredentialUpdateOne {
	if v != nil {
		_u.SetQuotaObserved(*v)
	}
	return _u
}

// ClearQuotaObserved clears the value of the "quota_observed" field.
func (_u *CPACredentialUpdateOne) ClearQuotaObserved() *CPACredentialUpdateOne {
	_u.mutation.ClearQuotaObserved()
	return _u
}

// Mutation returns the CPACredentialMutation object of the builder.
func (_u *CPACredentialUpdateOne) Mutation() *CPACredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the CPACredentialUpdate builder.
func (_u *CPACredentialUpdateOne) Where(ps ...predicate.CPACredential) *CPACredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CPACredentialUpdateOne) Select(field string, fields ...string) *CPACredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CPACredential entity.
func (_u *CPACredentialUpdateOne) Save(ctx context.Context) (*CPACredential, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CPACredentialUpdateOne) SaveX(ctx context.Context) *CPACredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CPACredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CPACredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CPACredentialUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if cpacredential.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpacredential.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cpacredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CPACredentialUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalKey(); ok {
		if err := cpacredential.ExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "external_key", err: fmt.Errorf(`ent: validator failed for field "CPACredential.external_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RemoteName(); ok {
		if err := cpacredential.RemoteNameValidator(v); err != nil {
			return &ValidationError{Name: "remote_name", err: fmt.Errorf(`ent: validator failed for field "CPACredential.remote_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayName(); ok {
		if err := cpacredential.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "CPACredential.display_name": %w`, err)}
		}
	}
	if _u.mutation.CpaInstanceCleared() && len(_u.mutation.CpaInstanceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CPACredential.cpa_instance"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CPACredentialUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CPACredentialUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CPACredentialUpdateOne) sqlSave(ctx context.Context) (_node *CPACredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cpacredential.Table, cpacredential.Columns, sqlgraph.NewFieldSpec(cpacredential.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CPACredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cpacredential.FieldID)
		for _, f := range fields {
			if !cpacredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cpacredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cpacredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalKey(); ok {
		_spec.SetField(cpacredential.FieldExternalKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(cpacredential.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.RemoteName(); ok {
		_spec.SetField(cpacredential.FieldRemoteName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(cpacredential.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(cpacredential.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameSortKey(); ok {
		_spec.SetField(cpacredential.FieldDisplayNameSortKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameSortLength(); ok {
		_spec.SetField(cpacredential.FieldDisplayNameSortLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayNameSortLength(); ok {
		_spec.AddField(cpacredential.FieldDisplayNameSortLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(cpacredential.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(cpacredential.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(cpacredential.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusMessage(); ok {
		_spec.SetField(cpacredential.FieldStatusMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(cpacredential.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Unavailable(); ok {
		_spec.SetField(cpacredential.FieldUnavailable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RuntimeOnly(); ok {
		_spec.SetField(cpacredential.FieldRuntimeOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(cpacredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(cpacredential.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanType(); ok {
		_spec.SetField(cpacredential.FieldPlanType, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaContext(); ok {
		_spec.SetField(cpacredential.FieldQuotaContext, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.QuotaState(); ok {
		_spec.SetField(cpacredential.FieldQuotaState, field.TypeString, value)
	}
	if value, ok := _u.mutation.HealthState(); ok {
		_spec.SetField(cpacredential.FieldHealthState, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaCooling(); ok {
		_spec.SetField(cpacredential.FieldQuotaCooling, field.TypeBool, value)
	}
	if value, ok := _u.mutation.QuotaCooldownUntil(); ok {
		_spec.SetField(cpacredential.FieldQuotaCooldownUntil, field.TypeTime, value)
	}
	if _u.mutation.QuotaCooldownUntilCleared() {
		_spec.ClearField(cpacredential.FieldQuotaCooldownUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.ProjectionVersion(); ok {
		_spec.SetField(cpacredential.FieldProjectionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProjectionVersion(); ok {
		_spec.AddField(cpacredential.FieldProjectionVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaData(); ok {
		_spec.SetField(cpacredential.FieldQuotaData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.QuotaLastAttemptAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.QuotaLastAttemptAtCleared() {
		_spec.ClearField(cpacredential.FieldQuotaLastAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QuotaLastSuccessAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastSuccessAt, field.TypeTime, value)
	}
	if _u.mutation.QuotaLastSuccessAtCleared() {
		_spec.ClearField(cpacredential.FieldQuotaLastSuccessAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QuotaLastFailureAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastFailureAt, field.TypeTime, value)
	}
	if _u.mutation.QuotaLastFailureAtCleared() {
		_spec.ClearField(cpacredential.FieldQuotaLastFailureAt, field.TypeTime)
	}
	if value, ok := _u.mutation.QuotaLastError(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshLeaseToken(); ok {
		_spec.SetField(cpacredential.FieldRefreshLeaseToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshLeaseUntil(); ok {
		_spec.SetField(cpacredential.FieldRefreshLeaseUntil, field.TypeTime, value)
	}
	if _u.mutation.RefreshLeaseUntilCleared() {
		_spec.ClearField(cpacredential.FieldRefreshLeaseUntil, field.TypeTime)
	}
	if value, ok := _u.mutation.RefreshRevision(); ok {
		_spec.SetField(cpacredential.FieldRefreshRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshRevision(); ok {
		_spec.AddField(cpacredential.FieldRefreshRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.QuotaObserved(); ok {
		_spec.SetField(cpacredential.FieldQuotaObserved, field.TypeJSON, value)
	}
	if _u.mutation.QuotaObservedCleared() {
		_spec.ClearField(cpacredential.FieldQuotaObserved, field.TypeJSON)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CPACredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cpacredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
