// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/cpacredential"
	"github.com/looplj/axonhub/internal/ent/cpainstance"
	"github.com/looplj/axonhub/internal/objects"
)

// CPACredentialCreate is the builder for creating a CPACredential entity.
type CPACredentialCreate struct {
	config
	mutation *CPACredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CPACredentialCreate) SetCreatedAt(v time.Time) *CPACredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableCreatedAt(v *time.Time) *CPACredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CPACredentialCreate) SetUpdatedAt(v time.Time) *CPACredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableUpdatedAt(v *time.Time) *CPACredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (_c *CPACredentialCreate) SetCpaInstanceID(v int) *CPACredentialCreate {
	_c.mutation.SetCpaInstanceID(v)
	return _c
}

// SetExternalKey sets the "external_key" field.
func (_c *CPACredentialCreate) SetExternalKey(v string) *CPACredentialCreate {
	_c.mutation.SetExternalKey(v)
	return _c
}

// SetAuthIndex sets the "auth_index" field.
func (_c *CPACredentialCreate) SetAuthIndex(v string) *CPACredentialCreate {
	_c.mutation.SetAuthIndex(v)
	return _c
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableAuthIndex(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetAuthIndex(*v)
	}
	return _c
}

// SetRemoteName sets the "remote_name" field.
func (_c *CPACredentialCreate) SetRemoteName(v string) *CPACredentialCreate {
	_c.mutation.SetRemoteName(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *CPACredentialCreate) SetLabel(v string) *CPACredentialCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableLabel(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *CPACredentialCreate) SetDisplayName(v string) *CPACredentialCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *CPACredentialCreate) SetProvider(v string) *CPACredentialCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableProvider(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *CPACredentialCreate) SetEmail(v string) *CPACredentialCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableEmail(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *CPACredentialCreate) SetStatus(v string) *CPACredentialCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableStatus(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStatusMessage sets the "status_message" field.
func (_c *CPACredentialCreate) SetStatusMessage(v string) *CPACredentialCreate {
	_c.mutation.SetStatusMessage(v)
	return _c
}

// SetNillableStatusMessage sets the "status_message" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableStatusMessage(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetStatusMessage(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *CPACredentialCreate) SetDisabled(v bool) *CPACredentialCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableDisabled(v *bool) *CPACredentialCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetUnavailable sets the "unavailable" field.
func (_c *CPACredentialCreate) SetUnavailable(v bool) *CPACredentialCreate {
	_c.mutation.SetUnavailable(v)
	return _c
}

// SetNillableUnavailable sets the "unavailable" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableUnavailable(v *bool) *CPACredentialCreate {
	if v != nil {
		_c.SetUnavailable(*v)
	}
	return _c
}

// SetRuntimeOnly sets the "runtime_only" field.
func (_c *CPACredentialCreate) SetRuntimeOnly(v bool) *CPACredentialCreate {
	_c.mutation.SetRuntimeOnly(v)
	return _c
}

// SetNillableRuntimeOnly sets the "runtime_only" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableRuntimeOnly(v *bool) *CPACredentialCreate {
	if v != nil {
		_c.SetRuntimeOnly(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *CPACredentialCreate) SetPriority(v int) *CPACredentialCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillablePriority(v *int) *CPACredentialCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetPlanType sets the "plan_type" field.
func (_c *CPACredentialCreate) SetPlanType(v string) *CPACredentialCreate {
	_c.mutation.SetPlanType(v)
	return _c
}

// SetNillablePlanType sets the "plan_type" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillablePlanType(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetPlanType(*v)
	}
	return _c
}

// SetQuotaContext sets the "quota_context" field.
func (_c *CPACredentialCreate) SetQuotaContext(v objects.CPAQuotaContext) *CPACredentialCreate {
	_c.mutation.SetQuotaContext(v)
	return _c
}

// SetNillableQuotaContext sets the "quota_context" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaContext(v *objects.CPAQuotaContext) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaContext(*v)
	}
	return _c
}

// SetQuotaState sets the "quota_state" field.
func (_c *CPACredentialCreate) SetQuotaState(v string) *CPACredentialCreate {
	_c.mutation.SetQuotaState(v)
	return _c
}

// SetNillableQuotaState sets the "quota_state" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaState(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaState(*v)
	}
	return _c
}

// SetQuotaData sets the "quota_data" field.
func (_c *CPACredentialCreate) SetQuotaData(v objects.CPAQuotaSnapshot) *CPACredentialCreate {
	_c.mutation.SetQuotaData(v)
	return _c
}

// SetNillableQuotaData sets the "quota_data" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaData(v *objects.CPAQuotaSnapshot) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaData(*v)
	}
	return _c
}

// SetQuotaLastAttemptAt sets the "quota_last_attempt_at" field.
func (_c *CPACredentialCreate) SetQuotaLastAttemptAt(v time.Time) *CPACredentialCreate {
	_c.mutation.SetQuotaLastAttemptAt(v)
	return _c
}

// SetNillableQuotaLastAttemptAt sets the "quota_last_attempt_at" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaLastAttemptAt(v *time.Time) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaLastAttemptAt(*v)
	}
	return _c
}

// SetQuotaLastSuccessAt sets the "quota_last_success_at" field.
func (_c *CPACredentialCreate) SetQuotaLastSuccessAt(v time.Time) *CPACredentialCreate {
	_c.mutation.SetQuotaLastSuccessAt(v)
	return _c
}

// SetNillableQuotaLastSuccessAt sets the "quota_last_success_at" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaLastSuccessAt(v *time.Time) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaLastSuccessAt(*v)
	}
	return _c
}

// SetQuotaLastFailureAt sets the "quota_last_failure_at" field.
func (_c *CPACredentialCreate) SetQuotaLastFailureAt(v time.Time) *CPACredentialCreate {
	_c.mutation.SetQuotaLastFailureAt(v)
	return _c
}

// SetNillableQuotaLastFailureAt sets the "quota_last_failure_at" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaLastFailureAt(v *time.Time) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaLastFailureAt(*v)
	}
	return _c
}

// SetQuotaLastError sets the "quota_last_error" field.
func (_c *CPACredentialCreate) SetQuotaLastError(v string) *CPACredentialCreate {
	_c.mutation.SetQuotaLastError(v)
	return _c
}

// SetNillableQuotaLastError sets the "quota_last_error" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaLastError(v *string) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaLastError(*v)
	}
	return _c
}

// SetQuotaObserved sets the "quota_observed" field.
func (_c *CPACredentialCreate) SetQuotaObserved(v objects.CPAQuotaObserved) *CPACredentialCreate {
	_c.mutation.SetQuotaObserved(v)
	return _c
}

// SetNillableQuotaObserved sets the "quota_observed" field if the given value is not nil.
func (_c *CPACredentialCreate) SetNillableQuotaObserved(v *objects.CPAQuotaObserved) *CPACredentialCreate {
	if v != nil {
		_c.SetQuotaObserved(*v)
	}
	return _c
}

// SetCpaInstance sets the "cpa_instance" edge to the CPAInstance entity.
func (_c *CPACredentialCreate) SetCpaInstance(v *CPAInstance) *CPACredentialCreate {
	return _c.SetCpaInstanceID(v.ID)
}

// Mutation returns the CPACredentialMutation object of the builder.
func (_c *CPACredentialCreate) Mutation() *CPACredentialMutation {
	return _c.mutation
}

// Save creates the CPACredential in the database.
func (_c *CPACredentialCreate) Save(ctx context.Context) (*CPACredential, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CPACredentialCreate) SaveX(ctx context.Context) *CPACredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CPACredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CPACredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CPACredentialCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if cpacredential.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpacredential.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := cpacredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if cpacredential.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpacredential.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cpacredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		v := cpacredential.DefaultAuthIndex
		_c.mutation.SetAuthIndex(v)
	}
	if _, ok := _c.mutation.Label(); !ok {
		v := cpacredential.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := cpacredential.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := cpacredential.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := cpacredential.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StatusMessage(); !ok {
		v := cpacredential.DefaultStatusMessage
		_c.mutation.SetStatusMessage(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := cpacredential.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.Unavailable(); !ok {
		v := cpacredential.DefaultUnavailable
		_c.mutation.SetUnavailable(v)
	}
	if _, ok := _c.mutation.RuntimeOnly(); !ok {
		v := cpacredential.DefaultRuntimeOnly
		_c.mutation.SetRuntimeOnly(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := cpacredential.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.PlanType(); !ok {
		v := cpacredential.DefaultPlanType
		_c.mutation.SetPlanType(v)
	}
	if _, ok := _c.mutation.QuotaContext(); !ok {
		v := cpacredential.DefaultQuotaContext
		_c.mutation.SetQuotaContext(v)
	}
	if _, ok := _c.mutation.QuotaState(); !ok {
		v := cpacredential.DefaultQuotaState
		_c.mutation.SetQuotaState(v)
	}
	if _, ok := _c.mutation.QuotaData(); !ok {
		v := cpacredential.DefaultQuotaData
		_c.mutation.SetQuotaData(v)
	}
	if _, ok := _c.mutation.QuotaLastError(); !ok {
		v := cpacredential.DefaultQuotaLastError
		_c.mutation.SetQuotaLastError(v)
	}
	if _, ok := _c.mutation.QuotaObserved(); !ok {
		v := cpacredential.DefaultQuotaObserved
		_c.mutation.SetQuotaObserved(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CPACredentialCreate) check() error {
	if _, ok := _c.mutation.CpaInstanceID(); !ok {
		return &ValidationError{Name: "cpa_instance_id", err: errors.New(`ent: missing required field "CPACredential.cpa_instance_id"`)}
	}
	if _, ok := _c.mutation.ExternalKey(); !ok {
		return &ValidationError{Name: "external_key", err: errors.New(`ent: missing required field "CPACredential.external_key"`)}
	}
	if v, ok := _c.mutation.ExternalKey(); ok {
		if err := cpacredential.ExternalKeyValidator(v); err != nil {
			return &ValidationError{Name: "external_key", err: fmt.Errorf(`ent: validator failed for field "CPACredential.external_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		return &ValidationError{Name: "auth_index", err: errors.New(`ent: missing required field "CPACredential.auth_index"`)}
	}
	if _, ok := _c.mutation.RemoteName(); !ok {
		return &ValidationError{Name: "remote_name", err: errors.New(`ent: missing required field "CPACredential.remote_name"`)}
	}
	if v, ok := _c.mutation.RemoteName(); ok {
		if err := cpacredential.RemoteNameValidator(v); err != nil {
			return &ValidationError{Name: "remote_name", err: fmt.Errorf(`ent: validator failed for field "CPACredential.remote_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "CPACredential.label"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "CPACredential.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := cpacredential.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "CPACredential.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "CPACredential.provider"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "CPACredential.email"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CPACredential.status"`)}
	}
	if _, ok := _c.mutation.StatusMessage(); !ok {
		return &ValidationError{Name: "status_message", err: errors.New(`ent: missing required field "CPACredential.status_message"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "CPACredential.disabled"`)}
	}
	if _, ok := _c.mutation.Unavailable(); !ok {
		return &ValidationError{Name: "unavailable", err: errors.New(`ent: missing required field "CPACredential.unavailable"`)}
	}
	if _, ok := _c.mutation.RuntimeOnly(); !ok {
		return &ValidationError{Name: "runtime_only", err: errors.New(`ent: missing required field "CPACredential.runtime_only"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "CPACredential.priority"`)}
	}
	if _, ok := _c.mutation.PlanType(); !ok {
		return &ValidationError{Name: "plan_type", err: errors.New(`ent: missing required field "CPACredential.plan_type"`)}
	}
	if _, ok := _c.mutation.QuotaContext(); !ok {
		return &ValidationError{Name: "quota_context", err: errors.New(`ent: missing required field "CPACredential.quota_context"`)}
	}
	if _, ok := _c.mutation.QuotaState(); !ok {
		return &ValidationError{Name: "quota_state", err: errors.New(`ent: missing required field "CPACredential.quota_state"`)}
	}
	if _, ok := _c.mutation.QuotaData(); !ok {
		return &ValidationError{Name: "quota_data", err: errors.New(`ent: missing required field "CPACredential.quota_data"`)}
	}
	if _, ok := _c.mutation.QuotaLastError(); !ok {
		return &ValidationError{Name: "quota_last_error", err: errors.New(`ent: missing required field "CPACredential.quota_last_error"`)}
	}
	if len(_c.mutation.CpaInstanceIDs()) == 0 {
		return &ValidationError{Name: "cpa_instance", err: errors.New(`ent: missing required edge "CPACredential.cpa_instance"`)}
	}
	return nil
}

func (_c *CPACredentialCreate) sqlSave(ctx context.Context) (*CPACredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CPACredentialCreate) createSpec() (*CPACredential, *sqlgraph.CreateSpec) {
	var (
		_node = &CPACredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cpacredential.Table, sqlgraph.NewFieldSpec(cpacredential.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cpacredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cpacredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExternalKey(); ok {
		_spec.SetField(cpacredential.FieldExternalKey, field.TypeString, value)
		_node.ExternalKey = value
	}
	if value, ok := _c.mutation.AuthIndex(); ok {
		_spec.SetField(cpacredential.FieldAuthIndex, field.TypeString, value)
		_node.AuthIndex = value
	}
	if value, ok := _c.mutation.RemoteName(); ok {
		_spec.SetField(cpacredential.FieldRemoteName, field.TypeString, value)
		_node.RemoteName = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(cpacredential.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(cpacredential.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(cpacredential.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(cpacredential.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(cpacredential.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StatusMessage(); ok {
		_spec.SetField(cpacredential.FieldStatusMessage, field.TypeString, value)
		_node.StatusMessage = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(cpacredential.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.Unavailable(); ok {
		_spec.SetField(cpacredential.FieldUnavailable, field.TypeBool, value)
		_node.Unavailable = value
	}
	if value, ok := _c.mutation.RuntimeOnly(); ok {
		_spec.SetField(cpacredential.FieldRuntimeOnly, field.TypeBool, value)
		_node.RuntimeOnly = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(cpacredential.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.PlanType(); ok {
		_spec.SetField(cpacredential.FieldPlanType, field.TypeString, value)
		_node.PlanType = value
	}
	if value, ok := _c.mutation.QuotaContext(); ok {
		_spec.SetField(cpacredential.FieldQuotaContext, field.TypeJSON, value)
		_node.QuotaContext = value
	}
	if value, ok := _c.mutation.QuotaState(); ok {
		_spec.SetField(cpacredential.FieldQuotaState, field.TypeString, value)
		_node.QuotaState = value
	}
	if value, ok := _c.mutation.QuotaData(); ok {
		_spec.SetField(cpacredential.FieldQuotaData, field.TypeJSON, value)
		_node.QuotaData = value
	}
	if value, ok := _c.mutation.QuotaLastAttemptAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastAttemptAt, field.TypeTime, value)
		_node.QuotaLastAttemptAt = &value
	}
	if value, ok := _c.mutation.QuotaLastSuccessAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastSuccessAt, field.TypeTime, value)
		_node.QuotaLastSuccessAt = &value
	}
	if value, ok := _c.mutation.QuotaLastFailureAt(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastFailureAt, field.TypeTime, value)
		_node.QuotaLastFailureAt = &value
	}
	if value, ok := _c.mutation.QuotaLastError(); ok {
		_spec.SetField(cpacredential.FieldQuotaLastError, field.TypeString, value)
		_node.QuotaLastError = value
	}
	if value, ok := _c.mutation.QuotaObserved(); ok {
		_spec.SetField(cpacredential.FieldQuotaObserved, field.TypeJSON, value)
		_node.QuotaObserved = value
	}
	if nodes := _c.mutation.CpaInstanceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cpacredential.CpaInstanceTable,
			Columns: []string{cpacredential.CpaInstanceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cpainstance.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CpaInstanceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CPACredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CPACredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CPACredentialCreate) OnConflict(opts ...sql.ConflictOption) *CPACredentialUpsertOne {
	_c.conflict = opts
	return &CPACredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CPACredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CPACredentialCreate) OnConflictColumns(columns ...string) *CPACredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CPACredentialUpsertOne{
		create: _c,
	}
}

type (
	// CPACredentialUpsertOne is the builder for "upsert"-ing
	//  one CPACredential node.
	CPACredentialUpsertOne struct {
		create *CPACredentialCreate
	}

	// CPACredentialUpsert is the "OnConflict" setter.
	CPACredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CPACredentialUpsert) SetUpdatedAt(v time.Time) *CPACredentialUpsert {
	u.Set(cpacredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateUpdatedAt() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldUpdatedAt)
	return u
}

// SetExternalKey sets the "external_key" field.
func (u *CPACredentialUpsert) SetExternalKey(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldExternalKey, v)
	return u
}

// UpdateExternalKey sets the "external_key" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateExternalKey() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldExternalKey)
	return u
}

// SetAuthIndex sets the "auth_index" field.
func (u *CPACredentialUpsert) SetAuthIndex(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldAuthIndex, v)
	return u
}

// UpdateAuthIndex sets the "auth_index" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateAuthIndex() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldAuthIndex)
	return u
}

// SetRemoteName sets the "remote_name" field.
func (u *CPACredentialUpsert) SetRemoteName(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldRemoteName, v)
	return u
}

// UpdateRemoteName sets the "remote_name" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateRemoteName() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldRemoteName)
	return u
}

// SetLabel sets the "label" field.
func (u *CPACredentialUpsert) SetLabel(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateLabel() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldLabel)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *CPACredentialUpsert) SetDisplayName(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateDisplayName() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldDisplayName)
	return u
}

// SetProvider sets the "provider" field.
func (u *CPACredentialUpsert) SetProvider(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateProvider() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldProvider)
	return u
}

// SetEmail sets the "email" field.
func (u *CPACredentialUpsert) SetEmail(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateEmail() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldEmail)
	return u
}

// SetStatus sets the "status" field.
func (u *CPACredentialUpsert) SetStatus(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateStatus() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldStatus)
	return u
}

// SetStatusMessage sets the "status_message" field.
func (u *CPACredentialUpsert) SetStatusMessage(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldStatusMessage, v)
	return u
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateStatusMessage() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldStatusMessage)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *CPACredentialUpsert) SetDisabled(v bool) *CPACredentialUpsert {
	u.Set(cpacredential.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateDisabled() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldDisabled)
	return u
}

// SetUnavailable sets the "unavailable" field.
func (u *CPACredentialUpsert) SetUnavailable(v bool) *CPACredentialUpsert {
	u.Set(cpacredential.FieldUnavailable, v)
	return u
}

// UpdateUnavailable sets the "unavailable" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateUnavailable() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldUnavailable)
	return u
}

// SetRuntimeOnly sets the "runtime_only" field.
func (u *CPACredentialUpsert) SetRuntimeOnly(v bool) *CPACredentialUpsert {
	u.Set(cpacredential.FieldRuntimeOnly, v)
	return u
}

// UpdateRuntimeOnly sets the "runtime_only" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateRuntimeOnly() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldRuntimeOnly)
	return u
}

// SetPriority sets the "priority" field.
func (u *CPACredentialUpsert) SetPriority(v int) *CPACredentialUpsert {
	u.Set(cpacredential.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdatePriority() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *CPACredentialUpsert) AddPriority(v int) *CPACredentialUpsert {
	u.Add(cpacredential.FieldPriority, v)
	return u
}

// SetPlanType sets the "plan_type" field.
func (u *CPACredentialUpsert) SetPlanType(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldPlanType, v)
	return u
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdatePlanType() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldPlanType)
	return u
}

// SetQuotaContext sets the "quota_context" field.
func (u *CPACredentialUpsert) SetQuotaContext(v objects.CPAQuotaContext) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaContext, v)
	return u
}

// UpdateQuotaContext sets the "quota_context" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaContext() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaContext)
	return u
}

// SetQuotaState sets the "quota_state" field.
func (u *CPACredentialUpsert) SetQuotaState(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaState, v)
	return u
}

// UpdateQuotaState sets the "quota_state" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaState() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaState)
	return u
}

// SetQuotaData sets the "quota_data" field.
func (u *CPACredentialUpsert) SetQuotaData(v objects.CPAQuotaSnapshot) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaData, v)
	return u
}

// UpdateQuotaData sets the "quota_data" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaData() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaData)
	return u
}

// SetQuotaLastAttemptAt sets the "quota_last_attempt_at" field.
func (u *CPACredentialUpsert) SetQuotaLastAttemptAt(v time.Time) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaLastAttemptAt, v)
	return u
}

// UpdateQuotaLastAttemptAt sets the "quota_last_attempt_at" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaLastAttemptAt() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaLastAttemptAt)
	return u
}

// ClearQuotaLastAttemptAt clears the value of the "quota_last_attempt_at" field.
func (u *CPACredentialUpsert) ClearQuotaLastAttemptAt() *CPACredentialUpsert {
	u.SetNull(cpacredential.FieldQuotaLastAttemptAt)
	return u
}

// SetQuotaLastSuccessAt sets the "quota_last_success_at" field.
func (u *CPACredentialUpsert) SetQuotaLastSuccessAt(v time.Time) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaLastSuccessAt, v)
	return u
}

// UpdateQuotaLastSuccessAt sets the "quota_last_success_at" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaLastSuccessAt() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaLastSuccessAt)
	return u
}

// ClearQuotaLastSuccessAt clears the value of the "quota_last_success_at" field.
func (u *CPACredentialUpsert) ClearQuotaLastSuccessAt() *CPACredentialUpsert {
	u.SetNull(cpacredential.FieldQuotaLastSuccessAt)
	return u
}

// SetQuotaLastFailureAt sets the "quota_last_failure_at" field.
func (u *CPACredentialUpsert) SetQuotaLastFailureAt(v time.Time) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaLastFailureAt, v)
	return u
}

// UpdateQuotaLastFailureAt sets the "quota_last_failure_at" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaLastFailureAt() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaLastFailureAt)
	return u
}

// ClearQuotaLastFailureAt clears the value of the "quota_last_failure_at" field.
func (u *CPACredentialUpsert) ClearQuotaLastFailureAt() *CPACredentialUpsert {
	u.SetNull(cpacredential.FieldQuotaLastFailureAt)
	return u
}

// SetQuotaLastError sets the "quota_last_error" field.
func (u *CPACredentialUpsert) SetQuotaLastError(v string) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaLastError, v)
	return u
}

// UpdateQuotaLastError sets the "quota_last_error" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaLastError() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaLastError)
	return u
}

// SetQuotaObserved sets the "quota_observed" field.
func (u *CPACredentialUpsert) SetQuotaObserved(v objects.CPAQuotaObserved) *CPACredentialUpsert {
	u.Set(cpacredential.FieldQuotaObserved, v)
	return u
}

// UpdateQuotaObserved sets the "quota_observed" field to the value that was provided on create.
func (u *CPACredentialUpsert) UpdateQuotaObserved() *CPACredentialUpsert {
	u.SetExcluded(cpacredential.FieldQuotaObserved)
	return u
}

// ClearQuotaObserved clears the value of the "quota_observed" field.
func (u *CPACredentialUpsert) ClearQuotaObserved() *CPACredentialUpsert {
	u.SetNull(cpacredential.FieldQuotaObserved)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CPACredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CPACredentialUpsertOne) UpdateNewValues() *CPACredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cpacredential.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.CpaInstanceID(); exists {
			s.SetIgnore(cpacredential.FieldCpaInstanceID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CPACredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CPACredentialUpsertOne) Ignore() *CPACredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CPACredentialUpsertOne) DoNothing() *CPACredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CPACredentialCreate.OnConflict
// documentation for more info.
func (u *CPACredentialUpsertOne) Update(set func(*CPACredentialUpsert)) *CPACredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CPACredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CPACredentialUpsertOne) SetUpdatedAt(v time.Time) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateUpdatedAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetExternalKey sets the "external_key" field.
func (u *CPACredentialUpsertOne) SetExternalKey(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetExternalKey(v)
	})
}

// UpdateExternalKey sets the "external_key" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateExternalKey() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateExternalKey()
	})
}

// SetAuthIndex sets the "auth_index" field.
func (u *CPACredentialUpsertOne) SetAuthIndex(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetAuthIndex(v)
	})
}

// UpdateAuthIndex sets the "auth_index" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateAuthIndex() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateAuthIndex()
	})
}

// SetRemoteName sets the "remote_name" field.
func (u *CPACredentialUpsertOne) SetRemoteName(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetRemoteName(v)
	})
}

// UpdateRemoteName sets the "remote_name" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateRemoteName() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateRemoteName()
	})
}

// SetLabel sets the "label" field.
func (u *CPACredentialUpsertOne) SetLabel(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateLabel() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateLabel()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *CPACredentialUpsertOne) SetDisplayName(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateDisplayName() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateDisplayName()
	})
}

// SetProvider sets the "provider" field.
func (u *CPACredentialUpsertOne) SetProvider(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateProvider() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateProvider()
	})
}

// SetEmail sets the "email" field.
func (u *CPACredentialUpsertOne) SetEmail(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateEmail() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateEmail()
	})
}

// SetStatus sets the "status" field.
func (u *CPACredentialUpsertOne) SetStatus(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateStatus() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateStatus()
	})
}

// SetStatusMessage sets the "status_message" field.
func (u *CPACredentialUpsertOne) SetStatusMessage(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetStatusMessage(v)
	})
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateStatusMessage() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateStatusMessage()
	})
}

// SetDisabled sets the "disabled" field.
func (u *CPACredentialUpsertOne) SetDisabled(v bool) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateDisabled() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateDisabled()
	})
}

// SetUnavailable sets the "unavailable" field.
func (u *CPACredentialUpsertOne) SetUnavailable(v bool) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetUnavailable(v)
	})
}

// UpdateUnavailable sets the "unavailable" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateUnavailable() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateUnavailable()
	})
}

// SetRuntimeOnly sets the "runtime_only" field.
func (u *CPACredentialUpsertOne) SetRuntimeOnly(v bool) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetRuntimeOnly(v)
	})
}

// UpdateRuntimeOnly sets the "runtime_only" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateRuntimeOnly() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateRuntimeOnly()
	})
}

// SetPriority sets the "priority" field.
func (u *CPACredentialUpsertOne) SetPriority(v int) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *CPACredentialUpsertOne) AddPriority(v int) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdatePriority() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdatePriority()
	})
}

// SetPlanType sets the "plan_type" field.
func (u *CPACredentialUpsertOne) SetPlanType(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetPlanType(v)
	})
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdatePlanType() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdatePlanType()
	})
}

// SetQuotaContext sets the "quota_context" field.
func (u *CPACredentialUpsertOne) SetQuotaContext(v objects.CPAQuotaContext) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaContext(v)
	})
}

// UpdateQuotaContext sets the "quota_context" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaContext() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaContext()
	})
}

// SetQuotaState sets the "quota_state" field.
func (u *CPACredentialUpsertOne) SetQuotaState(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaState(v)
	})
}

// UpdateQuotaState sets the "quota_state" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaState() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaState()
	})
}

// SetQuotaData sets the "quota_data" field.
func (u *CPACredentialUpsertOne) SetQuotaData(v objects.CPAQuotaSnapshot) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaData(v)
	})
}

// UpdateQuotaData sets the "quota_data" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaData() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaData()
	})
}

// SetQuotaLastAttemptAt sets the "quota_last_attempt_at" field.
func (u *CPACredentialUpsertOne) SetQuotaLastAttemptAt(v time.Time) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastAttemptAt(v)
	})
}

// UpdateQuotaLastAttemptAt sets the "quota_last_attempt_at" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaLastAttemptAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastAttemptAt()
	})
}

// ClearQuotaLastAttemptAt clears the value of the "quota_last_attempt_at" field.
func (u *CPACredentialUpsertOne) ClearQuotaLastAttemptAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaLastAttemptAt()
	})
}

// SetQuotaLastSuccessAt sets the "quota_last_success_at" field.
func (u *CPACredentialUpsertOne) SetQuotaLastSuccessAt(v time.Time) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastSuccessAt(v)
	})
}

// UpdateQuotaLastSuccessAt sets the "quota_last_success_at" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaLastSuccessAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastSuccessAt()
	})
}

// ClearQuotaLastSuccessAt clears the value of the "quota_last_success_at" field.
func (u *CPACredentialUpsertOne) ClearQuotaLastSuccessAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaLastSuccessAt()
	})
}

// SetQuotaLastFailureAt sets the "quota_last_failure_at" field.
func (u *CPACredentialUpsertOne) SetQuotaLastFailureAt(v time.Time) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastFailureAt(v)
	})
}

// UpdateQuotaLastFailureAt sets the "quota_last_failure_at" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaLastFailureAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastFailureAt()
	})
}

// ClearQuotaLastFailureAt clears the value of the "quota_last_failure_at" field.
func (u *CPACredentialUpsertOne) ClearQuotaLastFailureAt() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaLastFailureAt()
	})
}

// SetQuotaLastError sets the "quota_last_error" field.
func (u *CPACredentialUpsertOne) SetQuotaLastError(v string) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastError(v)
	})
}

// UpdateQuotaLastError sets the "quota_last_error" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaLastError() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastError()
	})
}

// SetQuotaObserved sets the "quota_observed" field.
func (u *CPACredentialUpsertOne) SetQuotaObserved(v objects.CPAQuotaObserved) *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaObserved(v)
	})
}

// UpdateQuotaObserved sets the "quota_observed" field to the value that was provided on create.
func (u *CPACredentialUpsertOne) UpdateQuotaObserved() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaObserved()
	})
}

// ClearQuotaObserved clears the value of the "quota_observed" field.
func (u *CPACredentialUpsertOne) ClearQuotaObserved() *CPACredentialUpsertOne {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaObserved()
	})
}

// Exec executes the query.
func (u *CPACredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CPACredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CPACredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CPACredentialUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CPACredentialUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CPACredentialCreateBulk is the builder for creating many CPACredential entities in bulk.
type CPACredentialCreateBulk struct {
	config
	err      error
	builders []*CPACredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the CPACredential entities in the database.
func (_c *CPACredentialCreateBulk) Save(ctx context.Context) ([]*CPACredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CPACredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CPACredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CPACredentialCreateBulk) SaveX(ctx context.Context) []*CPACredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CPACredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CPACredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CPACredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CPACredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CPACredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *CPACredentialUpsertBulk {
	_c.conflict = opts
	return &CPACredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CPACredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CPACredentialCreateBulk) OnConflictColumns(columns ...string) *CPACredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CPACredentialUpsertBulk{
		create: _c,
	}
}

// CPACredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of CPACredential nodes.
type CPACredentialUpsertBulk struct {
	create *CPACredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CPACredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CPACredentialUpsertBulk) UpdateNewValues() *CPACredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cpacredential.FieldCreatedAt)
			}
			if _, exists := b.mutation.CpaInstanceID(); exists {
				s.SetIgnore(cpacredential.FieldCpaInstanceID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CPACredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CPACredentialUpsertBulk) Ignore() *CPACredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CPACredentialUpsertBulk) DoNothing() *CPACredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CPACredentialCreateBulk.OnConflict
// documentation for more info.
func (u *CPACredentialUpsertBulk) Update(set func(*CPACredentialUpsert)) *CPACredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CPACredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CPACredentialUpsertBulk) SetUpdatedAt(v time.Time) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateUpdatedAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetExternalKey sets the "external_key" field.
func (u *CPACredentialUpsertBulk) SetExternalKey(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetExternalKey(v)
	})
}

// UpdateExternalKey sets the "external_key" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateExternalKey() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateExternalKey()
	})
}

// SetAuthIndex sets the "auth_index" field.
func (u *CPACredentialUpsertBulk) SetAuthIndex(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetAuthIndex(v)
	})
}

// UpdateAuthIndex sets the "auth_index" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateAuthIndex() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateAuthIndex()
	})
}

// SetRemoteName sets the "remote_name" field.
func (u *CPACredentialUpsertBulk) SetRemoteName(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetRemoteName(v)
	})
}

// UpdateRemoteName sets the "remote_name" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateRemoteName() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateRemoteName()
	})
}

// SetLabel sets the "label" field.
func (u *CPACredentialUpsertBulk) SetLabel(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateLabel() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateLabel()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *CPACredentialUpsertBulk) SetDisplayName(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateDisplayName() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateDisplayName()
	})
}

// SetProvider sets the "provider" field.
func (u *CPACredentialUpsertBulk) SetProvider(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateProvider() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateProvider()
	})
}

// SetEmail sets the "email" field.
func (u *CPACredentialUpsertBulk) SetEmail(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateEmail() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateEmail()
	})
}

// SetStatus sets the "status" field.
func (u *CPACredentialUpsertBulk) SetStatus(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateStatus() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateStatus()
	})
}

// SetStatusMessage sets the "status_message" field.
func (u *CPACredentialUpsertBulk) SetStatusMessage(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetStatusMessage(v)
	})
}

// UpdateStatusMessage sets the "status_message" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateStatusMessage() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateStatusMessage()
	})
}

// SetDisabled sets the "disabled" field.
func (u *CPACredentialUpsertBulk) SetDisabled(v bool) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateDisabled() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateDisabled()
	})
}

// SetUnavailable sets the "unavailable" field.
func (u *CPACredentialUpsertBulk) SetUnavailable(v bool) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetUnavailable(v)
	})
}

// UpdateUnavailable sets the "unavailable" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateUnavailable() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateUnavailable()
	})
}

// SetRuntimeOnly sets the "runtime_only" field.
func (u *CPACredentialUpsertBulk) SetRuntimeOnly(v bool) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetRuntimeOnly(v)
	})
}

// UpdateRuntimeOnly sets the "runtime_only" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateRuntimeOnly() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateRuntimeOnly()
	})
}

// SetPriority sets the "priority" field.
func (u *CPACredentialUpsertBulk) SetPriority(v int) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *CPACredentialUpsertBulk) AddPriority(v int) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdatePriority() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdatePriority()
	})
}

// SetPlanType sets the "plan_type" field.
func (u *CPACredentialUpsertBulk) SetPlanType(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetPlanType(v)
	})
}

// UpdatePlanType sets the "plan_type" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdatePlanType() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdatePlanType()
	})
}

// SetQuotaContext sets the "quota_context" field.
func (u *CPACredentialUpsertBulk) SetQuotaContext(v objects.CPAQuotaContext) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaContext(v)
	})
}

// UpdateQuotaContext sets the "quota_context" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaContext() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaContext()
	})
}

// SetQuotaState sets the "quota_state" field.
func (u *CPACredentialUpsertBulk) SetQuotaState(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaState(v)
	})
}

// UpdateQuotaState sets the "quota_state" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaState() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaState()
	})
}

// SetQuotaData sets the "quota_data" field.
func (u *CPACredentialUpsertBulk) SetQuotaData(v objects.CPAQuotaSnapshot) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaData(v)
	})
}

// UpdateQuotaData sets the "quota_data" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaData() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaData()
	})
}

// SetQuotaLastAttemptAt sets the "quota_last_attempt_at" field.
func (u *CPACredentialUpsertBulk) SetQuotaLastAttemptAt(v time.Time) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastAttemptAt(v)
	})
}

// UpdateQuotaLastAttemptAt sets the "quota_last_attempt_at" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaLastAttemptAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastAttemptAt()
	})
}

// ClearQuotaLastAttemptAt clears the value of the "quota_last_attempt_at" field.
func (u *CPACredentialUpsertBulk) ClearQuotaLastAttemptAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaLastAttemptAt()
	})
}

// SetQuotaLastSuccessAt sets the "quota_last_success_at" field.
func (u *CPACredentialUpsertBulk) SetQuotaLastSuccessAt(v time.Time) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastSuccessAt(v)
	})
}

// UpdateQuotaLastSuccessAt sets the "quota_last_success_at" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaLastSuccessAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastSuccessAt()
	})
}

// ClearQuotaLastSuccessAt clears the value of the "quota_last_success_at" field.
func (u *CPACredentialUpsertBulk) ClearQuotaLastSuccessAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaLastSuccessAt()
	})
}

// SetQuotaLastFailureAt sets the "quota_last_failure_at" field.
func (u *CPACredentialUpsertBulk) SetQuotaLastFailureAt(v time.Time) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastFailureAt(v)
	})
}

// UpdateQuotaLastFailureAt sets the "quota_last_failure_at" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaLastFailureAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastFailureAt()
	})
}

// ClearQuotaLastFailureAt clears the value of the "quota_last_failure_at" field.
func (u *CPACredentialUpsertBulk) ClearQuotaLastFailureAt() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaLastFailureAt()
	})
}

// SetQuotaLastError sets the "quota_last_error" field.
func (u *CPACredentialUpsertBulk) SetQuotaLastError(v string) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaLastError(v)
	})
}

// UpdateQuotaLastError sets the "quota_last_error" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaLastError() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaLastError()
	})
}

// SetQuotaObserved sets the "quota_observed" field.
func (u *CPACredentialUpsertBulk) SetQuotaObserved(v objects.CPAQuotaObserved) *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.SetQuotaObserved(v)
	})
}

// UpdateQuotaObserved sets the "quota_observed" field to the value that was provided on create.
func (u *CPACredentialUpsertBulk) UpdateQuotaObserved() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.UpdateQuotaObserved()
	})
}

// ClearQuotaObserved clears the value of the "quota_observed" field.
func (u *CPACredentialUpsertBulk) ClearQuotaObserved() *CPACredentialUpsertBulk {
	return u.Update(func(s *CPACredentialUpsert) {
		s.ClearQuotaObserved()
	})
}

// Exec executes the query.
func (u *CPACredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CPACredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CPACredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CPACredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
