// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/cpacodexresetattempt"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// CPACodexResetAttemptDelete is the builder for deleting a CPACodexResetAttempt entity.
type CPACodexResetAttemptDelete struct {
	config
	hooks    []Hook
	mutation *CPACodexResetAttemptMutation
}

// Where appends a list predicates to the CPACodexResetAttemptDelete builder.
func (_d *CPACodexResetAttemptDelete) Where(ps ...predicate.CPACodexResetAttempt) *CPACodexResetAttemptDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CPACodexResetAttemptDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CPACodexResetAttemptDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CPACodexResetAttemptDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cpacodexresetattempt.Table, sqlgraph.NewFieldSpec(cpacodexresetattempt.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CPACodexResetAttemptDeleteOne is the builder for deleting a single CPACodexResetAttempt entity.
type CPACodexResetAttemptDeleteOne struct {
	_d *CPACodexResetAttemptDelete
}

// Where appends a list predicates to the CPACodexResetAttemptDelete builder.
func (_d *CPACodexResetAttemptDeleteOne) Where(ps ...predicate.CPACodexResetAttempt) *CPACodexResetAttemptDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CPACodexResetAttemptDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cpacodexresetattempt.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CPACodexResetAttemptDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
