// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/cpacredential"
	"github.com/looplj/axonhub/internal/ent/cpainstance"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// CPACredentialQuery is the builder for querying CPACredential entities.
type CPACredentialQuery struct {
	config
	ctx             *QueryContext
	order           []cpacredential.OrderOption
	inters          []Interceptor
	predicates      []predicate.CPACredential
	withCpaInstance *CPAInstanceQuery
	loadTotal       []func(context.Context, []*CPACredential) error
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CPACredentialQuery builder.
func (_q *CPACredentialQuery) Where(ps ...predicate.CPACredential) *CPACredentialQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CPACredentialQuery) Limit(limit int) *CPACredentialQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CPACredentialQuery) Offset(offset int) *CPACredentialQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CPACredentialQuery) Unique(unique bool) *CPACredentialQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CPACredentialQuery) Order(o ...cpacredential.OrderOption) *CPACredentialQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCpaInstance chains the current query on the "cpa_instance" edge.
func (_q *CPACredentialQuery) QueryCpaInstance() *CPAInstanceQuery {
	query := (&CPAInstanceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(cpacredential.Table, cpacredential.FieldID, selector),
			sqlgraph.To(cpainstance.Table, cpainstance.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, cpacredential.CpaInstanceTable, cpacredential.CpaInstanceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CPACredential entity from the query.
// Returns a *NotFoundError when no CPACredential was found.
func (_q *CPACredentialQuery) First(ctx context.Context) (*CPACredential, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{cpacredential.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CPACredentialQuery) FirstX(ctx context.Context) *CPACredential {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CPACredential ID from the query.
// Returns a *NotFoundError when no CPACredential ID was found.
func (_q *CPACredentialQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{cpacredential.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CPACredentialQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CPACredential entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CPACredential entity is found.
// Returns a *NotFoundError when no CPACredential entities are found.
func (_q *CPACredentialQuery) Only(ctx context.Context) (*CPACredential, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{cpacredential.Label}
	default:
		return nil, &NotSingularError{cpacredential.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CPACredentialQuery) OnlyX(ctx context.Context) *CPACredential {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CPACredential ID in the query.
// Returns a *NotSingularError when more than one CPACredential ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CPACredentialQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{cpacredential.Label}
	default:
		err = &NotSingularError{cpacredential.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CPACredentialQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CPACredentials.
func (_q *CPACredentialQuery) All(ctx context.Context) ([]*CPACredential, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CPACredential, *CPACredentialQuery]()
	return withInterceptors[[]*CPACredential](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CPACredentialQuery) AllX(ctx context.Context) []*CPACredential {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CPACredential IDs.
func (_q *CPACredentialQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(cpacredential.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CPACredentialQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CPACredentialQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CPACredentialQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CPACredentialQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CPACredentialQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CPACredentialQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CPACredentialQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CPACredentialQuery) Clone() *CPACredentialQuery {
	if _q == nil {
		return nil
	}
	return &CPACredentialQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]cpacredential.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.CPACredential{}, _q.predicates...),
		withCpaInstance: _q.withCpaInstance.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithCpaInstance tells the query-builder to eager-load the nodes that are connected to
// the "cpa_instance" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CPACredentialQuery) WithCpaInstance(opts ...func(*CPAInstanceQuery)) *CPACredentialQuery {
	query := (&CPAInstanceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCpaInstance = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CPACredential.Query().
//		GroupBy(cpacredential.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CPACredentialQuery) GroupBy(field string, fields ...string) *CPACredentialGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CPACredentialGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = cpacredential.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CPACredential.Query().
//		Select(cpacredential.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *CPACredentialQuery) Select(fields ...string) *CPACredentialSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CPACredentialSelect{CPACredentialQuery: _q}
	sbuild.label = cpacredential.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CPACredentialSelect configured with the given aggregations.
func (_q *CPACredentialQuery) Aggregate(fns ...AggregateFunc) *CPACredentialSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CPACredentialQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !cpacredential.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if cpacredential.Policy == nil {
		return errors.New("ent: uninitialized cpacredential.Policy (forgotten import ent/runtime?)")
	}
	if err := cpacredential.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *CPACredentialQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CPACredential, error) {
	var (
		nodes       = []*CPACredential{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withCpaInstance != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CPACredential).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CPACredential{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCpaInstance; query != nil {
		if err := _q.loadCpaInstance(ctx, query, nodes, nil,
			func(n *CPACredential, e *CPAInstance) { n.Edges.CpaInstance = e }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CPACredentialQuery) loadCpaInstance(ctx context.Context, query *CPAInstanceQuery, nodes []*CPACredential, init func(*CPACredential), assign func(*CPACredential, *CPAInstance)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*CPACredential)
	for i := range nodes {
		fk := nodes[i].CpaInstanceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cpainstance.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "cpa_instance_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CPACredentialQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CPACredentialQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(cpacredential.Table, cpacredential.Columns, sqlgraph.NewFieldSpec(cpacredential.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cpacredential.FieldID)
		for i := range fields {
			if fields[i] != cpacredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCpaInstance != nil {
			_spec.Node.AddColumnOnce(cpacredential.FieldCpaInstanceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CPACredentialQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(cpacredential.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = cpacredential.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *CPACredentialQuery) Modify(modifiers ...func(s *sql.Selector)) *CPACredentialSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// CPACredentialGroupBy is the group-by builder for CPACredential entities.
type CPACredentialGroupBy struct {
	selector
	build *CPACredentialQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CPACredentialGroupBy) Aggregate(fns ...AggregateFunc) *CPACredentialGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CPACredentialGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CPACredentialQuery, *CPACredentialGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CPACredentialGroupBy) sqlScan(ctx context.Context, root *CPACredentialQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CPACredentialSelect is the builder for selecting fields of CPACredential entities.
type CPACredentialSelect struct {
	*CPACredentialQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CPACredentialSelect) Aggregate(fns ...AggregateFunc) *CPACredentialSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CPACredentialSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CPACredentialQuery, *CPACredentialSelect](ctx, _s.CPACredentialQuery, _s, _s.inters, v)
}

func (_s *CPACredentialSelect) sqlScan(ctx context.Context, root *CPACredentialQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *CPACredentialSelect) Modify(modifiers ...func(s *sql.Selector)) *CPACredentialSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
