// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/cpainstance"
)

// CPAInstance is the model entity for the CPAInstance schema.
type CPAInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// BaseURL holds the value of the "base_url" field.
	BaseURL string `json:"base_url,omitempty"`
	// EncryptedSecret holds the value of the "encrypted_secret" field.
	EncryptedSecret string `json:"-"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// InsecureSkipTLS holds the value of the "insecure_skip_tls" field.
	InsecureSkipTLS bool `json:"insecure_skip_tls,omitempty"`
	// AutoRefreshEnabled holds the value of the "auto_refresh_enabled" field.
	AutoRefreshEnabled bool `json:"auto_refresh_enabled,omitempty"`
	// UsageStreamEnabled holds the value of the "usage_stream_enabled" field.
	UsageStreamEnabled bool `json:"usage_stream_enabled,omitempty"`
	// UsageCollectorID holds the value of the "usage_collector_id" field.
	UsageCollectorID string `json:"usage_collector_id,omitempty"`
	// RefreshIntervalMinutes holds the value of the "refresh_interval_minutes" field.
	RefreshIntervalMinutes int `json:"refresh_interval_minutes,omitempty"`
	// NextRefreshAt holds the value of the "next_refresh_at" field.
	NextRefreshAt *time.Time `json:"next_refresh_at,omitempty"`
	// AutoManageEnabled holds the value of the "auto_manage_enabled" field.
	AutoManageEnabled bool `json:"auto_manage_enabled,omitempty"`
	// AutoResetEnabled holds the value of the "auto_reset_enabled" field.
	AutoResetEnabled bool `json:"auto_reset_enabled,omitempty"`
	// EnabledPatrolIntervalMinutes holds the value of the "enabled_patrol_interval_minutes" field.
	EnabledPatrolIntervalMinutes int `json:"enabled_patrol_interval_minutes,omitempty"`
	// DisabledPatrolIntervalMinutes holds the value of the "disabled_patrol_interval_minutes" field.
	DisabledPatrolIntervalMinutes int `json:"disabled_patrol_interval_minutes,omitempty"`
	// NextEnabledPatrolAt holds the value of the "next_enabled_patrol_at" field.
	NextEnabledPatrolAt *time.Time `json:"next_enabled_patrol_at,omitempty"`
	// NextDisabledPatrolAt holds the value of the "next_disabled_patrol_at" field.
	NextDisabledPatrolAt *time.Time `json:"next_disabled_patrol_at,omitempty"`
	// ServerVersion holds the value of the "server_version" field.
	ServerVersion string `json:"server_version,omitempty"`
	// ServerCommit holds the value of the "server_commit" field.
	ServerCommit string `json:"server_commit,omitempty"`
	// ServerBuildDate holds the value of the "server_build_date" field.
	ServerBuildDate string `json:"server_build_date,omitempty"`
	// LastSyncAttemptAt holds the value of the "last_sync_attempt_at" field.
	LastSyncAttemptAt *time.Time `json:"last_sync_attempt_at,omitempty"`
	// LastSyncSuccessAt holds the value of the "last_sync_success_at" field.
	LastSyncSuccessAt *time.Time `json:"last_sync_success_at,omitempty"`
	// LastErrorAt holds the value of the "last_error_at" field.
	LastErrorAt *time.Time `json:"last_error_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CPAInstanceQuery when eager-loading is set.
	Edges        CPAInstanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CPAInstanceEdges holds the relations/edges for other nodes in the graph.
type CPAInstanceEdges struct {
	// Credentials holds the value of the credentials edge.
	Credentials []*CPACredential `json:"credentials,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool

	namedCredentials map[string][]*CPACredential
}

// CredentialsOrErr returns the Credentials value or an error if the edge
// was not loaded in eager-loading.
func (e CPAInstanceEdges) CredentialsOrErr() ([]*CPACredential, error) {
	if e.loadedTypes[0] {
		return e.Credentials, nil
	}
	return nil, &NotLoadedError{edge: "credentials"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CPAInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cpainstance.FieldEnabled, cpainstance.FieldInsecureSkipTLS, cpainstance.FieldAutoRefreshEnabled, cpainstance.FieldUsageStreamEnabled, cpainstance.FieldAutoManageEnabled, cpainstance.FieldAutoResetEnabled:
			values[i] = new(sql.NullBool)
		case cpainstance.FieldID, cpainstance.FieldRefreshIntervalMinutes, cpainstance.FieldEnabledPatrolIntervalMinutes, cpainstance.FieldDisabledPatrolIntervalMinutes:
			values[i] = new(sql.NullInt64)
		case cpainstance.FieldName, cpainstance.FieldBaseURL, cpainstance.FieldEncryptedSecret, cpainstance.FieldUsageCollectorID, cpainstance.FieldServerVersion, cpainstance.FieldServerCommit, cpainstance.FieldServerBuildDate, cpainstance.FieldLastError:
			values[i] = new(sql.NullString)
		case cpainstance.FieldCreatedAt, cpainstance.FieldUpdatedAt, cpainstance.FieldNextRefreshAt, cpainstance.FieldNextEnabledPatrolAt, cpainstance.FieldNextDisabledPatrolAt, cpainstance.FieldLastSyncAttemptAt, cpainstance.FieldLastSyncSuccessAt, cpainstance.FieldLastErrorAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CPAInstance fields.
func (_m *CPAInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cpainstance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cpainstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cpainstance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cpainstance.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case cpainstance.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case cpainstance.FieldEncryptedSecret:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_secret", values[i])
			} else if value.Valid {
				_m.EncryptedSecret = value.String
			}
		case cpainstance.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case cpainstance.FieldInsecureSkipTLS:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field insecure_skip_tls", values[i])
			} else if value.Valid {
				_m.InsecureSkipTLS = value.Bool
			}
		case cpainstance.FieldAutoRefreshEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_refresh_enabled", values[i])
			} else if value.Valid {
				_m.AutoRefreshEnabled = value.Bool
			}
		case cpainstance.FieldUsageStreamEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field usage_stream_enabled", values[i])
			} else if value.Valid {
				_m.UsageStreamEnabled = value.Bool
			}
		case cpainstance.FieldUsageCollectorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_collector_id", values[i])
			} else if value.Valid {
				_m.UsageCollectorID = value.String
			}
		case cpainstance.FieldRefreshIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval_minutes", values[i])
			} else if value.Valid {
				_m.RefreshIntervalMinutes = int(value.Int64)
			}
		case cpainstance.FieldNextRefreshAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_refresh_at", values[i])
			} else if value.Valid {
				_m.NextRefreshAt = new(time.Time)
				*_m.NextRefreshAt = value.Time
			}
		case cpainstance.FieldAutoManageEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_manage_enabled", values[i])
			} else if value.Valid {
				_m.AutoManageEnabled = value.Bool
			}
		case cpainstance.FieldAutoResetEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_reset_enabled", values[i])
			} else if value.Valid {
				_m.AutoResetEnabled = value.Bool
			}
		case cpainstance.FieldEnabledPatrolIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enabled_patrol_interval_minutes", values[i])
			} else if value.Valid {
				_m.EnabledPatrolIntervalMinutes = int(value.Int64)
			}
		case cpainstance.FieldDisabledPatrolIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field disabled_patrol_interval_minutes", values[i])
			} else if value.Valid {
				_m.DisabledPatrolIntervalMinutes = int(value.Int64)
			}
		case cpainstance.FieldNextEnabledPatrolAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_enabled_patrol_at", values[i])
			} else if value.Valid {
				_m.NextEnabledPatrolAt = new(time.Time)
				*_m.NextEnabledPatrolAt = value.Time
			}
		case cpainstance.FieldNextDisabledPatrolAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_disabled_patrol_at", values[i])
			} else if value.Valid {
				_m.NextDisabledPatrolAt = new(time.Time)
				*_m.NextDisabledPatrolAt = value.Time
			}
		case cpainstance.FieldServerVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_version", values[i])
			} else if value.Valid {
				_m.ServerVersion = value.String
			}
		case cpainstance.FieldServerCommit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_commit", values[i])
			} else if value.Valid {
				_m.ServerCommit = value.String
			}
		case cpainstance.FieldServerBuildDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_build_date", values[i])
			} else if value.Valid {
				_m.ServerBuildDate = value.String
			}
		case cpainstance.FieldLastSyncAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_attempt_at", values[i])
			} else if value.Valid {
				_m.LastSyncAttemptAt = new(time.Time)
				*_m.LastSyncAttemptAt = value.Time
			}
		case cpainstance.FieldLastSyncSuccessAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_success_at", values[i])
			} else if value.Valid {
				_m.LastSyncSuccessAt = new(time.Time)
				*_m.LastSyncSuccessAt = value.Time
			}
		case cpainstance.FieldLastErrorAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_at", values[i])
			} else if value.Valid {
				_m.LastErrorAt = new(time.Time)
				*_m.LastErrorAt = value.Time
			}
		case cpainstance.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CPAInstance.
// This includes values selected through modifiers, order, etc.
func (_m *CPAInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCredentials queries the "credentials" edge of the CPAInstance entity.
func (_m *CPAInstance) QueryCredentials() *CPACredentialQuery {
	return NewCPAInstanceClient(_m.config).QueryCredentials(_m)
}

// Update returns a builder for updating this CPAInstance.
// Note that you need to call CPAInstance.Unwrap() before calling this method if this CPAInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CPAInstance) Update() *CPAInstanceUpdateOne {
	return NewCPAInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CPAInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CPAInstance) Unwrap() *CPAInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CPAInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CPAInstance) String() string {
	var builder strings.Builder
	builder.WriteString("CPAInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("encrypted_secret=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("insecure_skip_tls=")
	builder.WriteString(fmt.Sprintf("%v", _m.InsecureSkipTLS))
	builder.WriteString(", ")
	builder.WriteString("auto_refresh_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoRefreshEnabled))
	builder.WriteString(", ")
	builder.WriteString("usage_stream_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageStreamEnabled))
	builder.WriteString(", ")
	builder.WriteString("usage_collector_id=")
	builder.WriteString(_m.UsageCollectorID)
	builder.WriteString(", ")
	builder.WriteString("refresh_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshIntervalMinutes))
	builder.WriteString(", ")
	if v := _m.NextRefreshAt; v != nil {
		builder.WriteString("next_refresh_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("auto_manage_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoManageEnabled))
	builder.WriteString(", ")
	builder.WriteString("auto_reset_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoResetEnabled))
	builder.WriteString(", ")
	builder.WriteString("enabled_patrol_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnabledPatrolIntervalMinutes))
	builder.WriteString(", ")
	builder.WriteString("disabled_patrol_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisabledPatrolIntervalMinutes))
	builder.WriteString(", ")
	if v := _m.NextEnabledPatrolAt; v != nil {
		builder.WriteString("next_enabled_patrol_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextDisabledPatrolAt; v != nil {
		builder.WriteString("next_disabled_patrol_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("server_version=")
	builder.WriteString(_m.ServerVersion)
	builder.WriteString(", ")
	builder.WriteString("server_commit=")
	builder.WriteString(_m.ServerCommit)
	builder.WriteString(", ")
	builder.WriteString("server_build_date=")
	builder.WriteString(_m.ServerBuildDate)
	builder.WriteString(", ")
	if v := _m.LastSyncAttemptAt; v != nil {
		builder.WriteString("last_sync_attempt_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastSyncSuccessAt; v != nil {
		builder.WriteString("last_sync_success_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastErrorAt; v != nil {
		builder.WriteString("last_error_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedCredentials returns the Credentials named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *CPAInstance) NamedCredentials(name string) ([]*CPACredential, error) {
	if _m.Edges.namedCredentials == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedCredentials[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *CPAInstance) appendNamedCredentials(name string, edges ...*CPACredential) {
	if _m.Edges.namedCredentials == nil {
		_m.Edges.namedCredentials = make(map[string][]*CPACredential)
	}
	if len(edges) == 0 {
		_m.Edges.namedCredentials[name] = []*CPACredential{}
	} else {
		_m.Edges.namedCredentials[name] = append(_m.Edges.namedCredentials[name], edges...)
	}
}

// CPAInstances is a parsable slice of CPAInstance.
type CPAInstances []*CPAInstance
