// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/cpausageevent"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// CpaUsageEventUpdate is the builder for updating CpaUsageEvent entities.
type CpaUsageEventUpdate struct {
	config
	hooks     []Hook
	mutation  *CpaUsageEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CpaUsageEventUpdate builder.
func (_u *CpaUsageEventUpdate) Where(ps ...predicate.CpaUsageEvent) *CpaUsageEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CpaUsageEventUpdate) SetUpdatedAt(v time.Time) *CpaUsageEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (_u *CpaUsageEventUpdate) SetCpaInstanceID(v int) *CpaUsageEventUpdate {
	_u.mutation.ResetCpaInstanceID()
	_u.mutation.SetCpaInstanceID(v)
	return _u
}

// SetNillableCpaInstanceID sets the "cpa_instance_id" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableCpaInstanceID(v *int) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetCpaInstanceID(*v)
	}
	return _u
}

// AddCpaInstanceID adds value to the "cpa_instance_id" field.
func (_u *CpaUsageEventUpdate) AddCpaInstanceID(v int) *CpaUsageEventUpdate {
	_u.mutation.AddCpaInstanceID(v)
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *CpaUsageEventUpdate) SetAuthIndex(v string) *CpaUsageEventUpdate {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableAuthIndex(v *string) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CpaUsageEventUpdate) SetProvider(v string) *CpaUsageEventUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableProvider(v *string) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *CpaUsageEventUpdate) SetModel(v string) *CpaUsageEventUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableModel(v *string) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *CpaUsageEventUpdate) SetSource(v string) *CpaUsageEventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableSource(v *string) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *CpaUsageEventUpdate) SetInputTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableInputTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *CpaUsageEventUpdate) AddInputTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *CpaUsageEventUpdate) SetOutputTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableOutputTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *CpaUsageEventUpdate) AddOutputTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *CpaUsageEventUpdate) SetReasoningTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableReasoningTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *CpaUsageEventUpdate) AddReasoningTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *CpaUsageEventUpdate) SetCachedTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableCachedTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *CpaUsageEventUpdate) AddCachedTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *CpaUsageEventUpdate) SetCacheReadTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableCacheReadTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *CpaUsageEventUpdate) AddCacheReadTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *CpaUsageEventUpdate) SetCacheCreationTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableCacheCreationTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *CpaUsageEventUpdate) AddCacheCreationTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *CpaUsageEventUpdate) SetTotalTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableTotalTokens(v *int64) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *CpaUsageEventUpdate) AddTotalTokens(v int64) *CpaUsageEventUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetFailed sets the "failed" field.
func (_u *CpaUsageEventUpdate) SetFailed(v bool) *CpaUsageEventUpdate {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableFailed(v *bool) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *CpaUsageEventUpdate) SetStatusCode(v int) *CpaUsageEventUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableStatusCode(v *int) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *CpaUsageEventUpdate) AddStatusCode(v int) *CpaUsageEventUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *CpaUsageEventUpdate) SetRequestedAt(v time.Time) *CpaUsageEventUpdate {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *CpaUsageEventUpdate) SetNillableRequestedAt(v *time.Time) *CpaUsageEventUpdate {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// Mutation returns the CpaUsageEventMutation object of the builder.
func (_u *CpaUsageEventUpdate) Mutation() *CpaUsageEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CpaUsageEventUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CpaUsageEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CpaUsageEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CpaUsageEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CpaUsageEventUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if cpausageevent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpausageevent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cpausageevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CpaUsageEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CpaUsageEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CpaUsageEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cpausageevent.Table, cpausageevent.Columns, sqlgraph.NewFieldSpec(cpausageevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cpausageevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CpaInstanceID(); ok {
		_spec.SetField(cpausageevent.FieldCpaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpaInstanceID(); ok {
		_spec.AddField(cpausageevent.FieldCpaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(cpausageevent.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(cpausageevent.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(cpausageevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(cpausageevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(cpausageevent.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(cpausageevent.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(cpausageevent.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(cpausageevent.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(cpausageevent.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(cpausageevent.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(cpausageevent.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(cpausageevent.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(cpausageevent.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(cpausageevent.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(cpausageevent.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(cpausageevent.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(cpausageevent.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(cpausageevent.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(cpausageevent.FieldFailed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(cpausageevent.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(cpausageevent.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(cpausageevent.FieldRequestedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cpausageevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CpaUsageEventUpdateOne is the builder for updating a single CpaUsageEvent entity.
type CpaUsageEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CpaUsageEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CpaUsageEventUpdateOne) SetUpdatedAt(v time.Time) *CpaUsageEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (_u *CpaUsageEventUpdateOne) SetCpaInstanceID(v int) *CpaUsageEventUpdateOne {
	_u.mutation.ResetCpaInstanceID()
	_u.mutation.SetCpaInstanceID(v)
	return _u
}

// SetNillableCpaInstanceID sets the "cpa_instance_id" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableCpaInstanceID(v *int) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetCpaInstanceID(*v)
	}
	return _u
}

// AddCpaInstanceID adds value to the "cpa_instance_id" field.
func (_u *CpaUsageEventUpdateOne) AddCpaInstanceID(v int) *CpaUsageEventUpdateOne {
	_u.mutation.AddCpaInstanceID(v)
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *CpaUsageEventUpdateOne) SetAuthIndex(v string) *CpaUsageEventUpdateOne {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableAuthIndex(v *string) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *CpaUsageEventUpdateOne) SetProvider(v string) *CpaUsageEventUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableProvider(v *string) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *CpaUsageEventUpdateOne) SetModel(v string) *CpaUsageEventUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableModel(v *string) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *CpaUsageEventUpdateOne) SetSource(v string) *CpaUsageEventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableSource(v *string) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetInputTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableInputTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddInputTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetOutputTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableOutputTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddOutputTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetReasoningTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableReasoningTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddReasoningTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetCachedTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableCachedTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddCachedTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetCacheReadTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableCacheReadTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddCacheReadTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetCacheCreationTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetCacheCreationTokens()
	_u.mutation.SetCacheCreationTokens(v)
	return _u
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableCacheCreationTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetCacheCreationTokens(*v)
	}
	return _u
}

// AddCacheCreationTokens adds value to the "cache_creation_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddCacheCreationTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddCacheCreationTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *CpaUsageEventUpdateOne) SetTotalTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableTotalTokens(v *int64) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *CpaUsageEventUpdateOne) AddTotalTokens(v int64) *CpaUsageEventUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetFailed sets the "failed" field.
func (_u *CpaUsageEventUpdateOne) SetFailed(v bool) *CpaUsageEventUpdateOne {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableFailed(v *bool) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *CpaUsageEventUpdateOne) SetStatusCode(v int) *CpaUsageEventUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableStatusCode(v *int) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *CpaUsageEventUpdateOne) AddStatusCode(v int) *CpaUsageEventUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetRequestedAt sets the "requested_at" field.
func (_u *CpaUsageEventUpdateOne) SetRequestedAt(v time.Time) *CpaUsageEventUpdateOne {
	_u.mutation.SetRequestedAt(v)
	return _u
}

// SetNillableRequestedAt sets the "requested_at" field if the given value is not nil.
func (_u *CpaUsageEventUpdateOne) SetNillableRequestedAt(v *time.Time) *CpaUsageEventUpdateOne {
	if v != nil {
		_u.SetRequestedAt(*v)
	}
	return _u
}

// Mutation returns the CpaUsageEventMutation object of the builder.
func (_u *CpaUsageEventUpdateOne) Mutation() *CpaUsageEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the CpaUsageEventUpdate builder.
func (_u *CpaUsageEventUpdateOne) Where(ps ...predicate.CpaUsageEvent) *CpaUsageEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CpaUsageEventUpdateOne) Select(field string, fields ...string) *CpaUsageEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CpaUsageEvent entity.
func (_u *CpaUsageEventUpdateOne) Save(ctx context.Context) (*CpaUsageEvent, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CpaUsageEventUpdateOne) SaveX(ctx context.Context) *CpaUsageEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CpaUsageEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CpaUsageEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CpaUsageEventUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if cpausageevent.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpausageevent.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cpausageevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CpaUsageEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CpaUsageEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CpaUsageEventUpdateOne) sqlSave(ctx context.Context) (_node *CpaUsageEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(cpausageevent.Table, cpausageevent.Columns, sqlgraph.NewFieldSpec(cpausageevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CpaUsageEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cpausageevent.FieldID)
		for _, f := range fields {
			if !cpausageevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cpausageevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cpausageevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CpaInstanceID(); ok {
		_spec.SetField(cpausageevent.FieldCpaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCpaInstanceID(); ok {
		_spec.AddField(cpausageevent.FieldCpaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(cpausageevent.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(cpausageevent.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(cpausageevent.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(cpausageevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(cpausageevent.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(cpausageevent.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(cpausageevent.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(cpausageevent.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(cpausageevent.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(cpausageevent.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(cpausageevent.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(cpausageevent.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(cpausageevent.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(cpausageevent.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheCreationTokens(); ok {
		_spec.SetField(cpausageevent.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheCreationTokens(); ok {
		_spec.AddField(cpausageevent.FieldCacheCreationTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(cpausageevent.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(cpausageevent.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(cpausageevent.FieldFailed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(cpausageevent.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(cpausageevent.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestedAt(); ok {
		_spec.SetField(cpausageevent.FieldRequestedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CpaUsageEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cpausageevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
