// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/cpausageevent"
)

// CpaUsageEventCreate is the builder for creating a CpaUsageEvent entity.
type CpaUsageEventCreate struct {
	config
	mutation *CpaUsageEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CpaUsageEventCreate) SetCreatedAt(v time.Time) *CpaUsageEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableCreatedAt(v *time.Time) *CpaUsageEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CpaUsageEventCreate) SetUpdatedAt(v time.Time) *CpaUsageEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableUpdatedAt(v *time.Time) *CpaUsageEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (_c *CpaUsageEventCreate) SetCpaInstanceID(v int) *CpaUsageEventCreate {
	_c.mutation.SetCpaInstanceID(v)
	return _c
}

// SetAuthIndex sets the "auth_index" field.
func (_c *CpaUsageEventCreate) SetAuthIndex(v string) *CpaUsageEventCreate {
	_c.mutation.SetAuthIndex(v)
	return _c
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableAuthIndex(v *string) *CpaUsageEventCreate {
	if v != nil {
		_c.SetAuthIndex(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *CpaUsageEventCreate) SetProvider(v string) *CpaUsageEventCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableProvider(v *string) *CpaUsageEventCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *CpaUsageEventCreate) SetModel(v string) *CpaUsageEventCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableModel(v *string) *CpaUsageEventCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *CpaUsageEventCreate) SetSource(v string) *CpaUsageEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableSource(v *string) *CpaUsageEventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *CpaUsageEventCreate) SetInputTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableInputTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *CpaUsageEventCreate) SetOutputTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableOutputTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_c *CpaUsageEventCreate) SetReasoningTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetReasoningTokens(v)
	return _c
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableReasoningTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetReasoningTokens(*v)
	}
	return _c
}

// SetCachedTokens sets the "cached_tokens" field.
func (_c *CpaUsageEventCreate) SetCachedTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetCachedTokens(v)
	return _c
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableCachedTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetCachedTokens(*v)
	}
	return _c
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_c *CpaUsageEventCreate) SetCacheReadTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetCacheReadTokens(v)
	return _c
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableCacheReadTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetCacheReadTokens(*v)
	}
	return _c
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (_c *CpaUsageEventCreate) SetCacheCreationTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetCacheCreationTokens(v)
	return _c
}

// SetNillableCacheCreationTokens sets the "cache_creation_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableCacheCreationTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetCacheCreationTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *CpaUsageEventCreate) SetTotalTokens(v int64) *CpaUsageEventCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableTotalTokens(v *int64) *CpaUsageEventCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetFailed sets the "failed" field.
func (_c *CpaUsageEventCreate) SetFailed(v bool) *CpaUsageEventCreate {
	_c.mutation.SetFailed(v)
	return _c
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableFailed(v *bool) *CpaUsageEventCreate {
	if v != nil {
		_c.SetFailed(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *CpaUsageEventCreate) SetStatusCode(v int) *CpaUsageEventCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *CpaUsageEventCreate) SetNillableStatusCode(v *int) *CpaUsageEventCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetRequestedAt sets the "requested_at" field.
func (_c *CpaUsageEventCreate) SetRequestedAt(v time.Time) *CpaUsageEventCreate {
	_c.mutation.SetRequestedAt(v)
	return _c
}

// Mutation returns the CpaUsageEventMutation object of the builder.
func (_c *CpaUsageEventCreate) Mutation() *CpaUsageEventMutation {
	return _c.mutation
}

// Save creates the CpaUsageEvent in the database.
func (_c *CpaUsageEventCreate) Save(ctx context.Context) (*CpaUsageEvent, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CpaUsageEventCreate) SaveX(ctx context.Context) *CpaUsageEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CpaUsageEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CpaUsageEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CpaUsageEventCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if cpausageevent.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpausageevent.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := cpausageevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if cpausageevent.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized cpausageevent.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := cpausageevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		v := cpausageevent.DefaultAuthIndex
		_c.mutation.SetAuthIndex(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := cpausageevent.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := cpausageevent.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := cpausageevent.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := cpausageevent.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := cpausageevent.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.ReasoningTokens(); !ok {
		v := cpausageevent.DefaultReasoningTokens
		_c.mutation.SetReasoningTokens(v)
	}
	if _, ok := _c.mutation.CachedTokens(); !ok {
		v := cpausageevent.DefaultCachedTokens
		_c.mutation.SetCachedTokens(v)
	}
	if _, ok := _c.mutation.CacheReadTokens(); !ok {
		v := cpausageevent.DefaultCacheReadTokens
		_c.mutation.SetCacheReadTokens(v)
	}
	if _, ok := _c.mutation.CacheCreationTokens(); !ok {
		v := cpausageevent.DefaultCacheCreationTokens
		_c.mutation.SetCacheCreationTokens(v)
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		v := cpausageevent.DefaultTotalTokens
		_c.mutation.SetTotalTokens(v)
	}
	if _, ok := _c.mutation.Failed(); !ok {
		v := cpausageevent.DefaultFailed
		_c.mutation.SetFailed(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := cpausageevent.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CpaUsageEventCreate) check() error {
	if _, ok := _c.mutation.CpaInstanceID(); !ok {
		return &ValidationError{Name: "cpa_instance_id", err: errors.New(`ent: missing required field "CpaUsageEvent.cpa_instance_id"`)}
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		return &ValidationError{Name: "auth_index", err: errors.New(`ent: missing required field "CpaUsageEvent.auth_index"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "CpaUsageEvent.provider"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "CpaUsageEvent.model"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "CpaUsageEvent.source"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.output_tokens"`)}
	}
	if _, ok := _c.mutation.ReasoningTokens(); !ok {
		return &ValidationError{Name: "reasoning_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.reasoning_tokens"`)}
	}
	if _, ok := _c.mutation.CachedTokens(); !ok {
		return &ValidationError{Name: "cached_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.cached_tokens"`)}
	}
	if _, ok := _c.mutation.CacheReadTokens(); !ok {
		return &ValidationError{Name: "cache_read_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.cache_read_tokens"`)}
	}
	if _, ok := _c.mutation.CacheCreationTokens(); !ok {
		return &ValidationError{Name: "cache_creation_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.cache_creation_tokens"`)}
	}
	if _, ok := _c.mutation.TotalTokens(); !ok {
		return &ValidationError{Name: "total_tokens", err: errors.New(`ent: missing required field "CpaUsageEvent.total_tokens"`)}
	}
	if _, ok := _c.mutation.Failed(); !ok {
		return &ValidationError{Name: "failed", err: errors.New(`ent: missing required field "CpaUsageEvent.failed"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "CpaUsageEvent.status_code"`)}
	}
	if _, ok := _c.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "CpaUsageEvent.requested_at"`)}
	}
	return nil
}

func (_c *CpaUsageEventCreate) sqlSave(ctx context.Context) (*CpaUsageEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CpaUsageEventCreate) createSpec() (*CpaUsageEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &CpaUsageEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cpausageevent.Table, sqlgraph.NewFieldSpec(cpausageevent.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cpausageevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cpausageevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CpaInstanceID(); ok {
		_spec.SetField(cpausageevent.FieldCpaInstanceID, field.TypeInt, value)
		_node.CpaInstanceID = value
	}
	if value, ok := _c.mutation.AuthIndex(); ok {
		_spec.SetField(cpausageevent.FieldAuthIndex, field.TypeString, value)
		_node.AuthIndex = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(cpausageevent.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(cpausageevent.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(cpausageevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(cpausageevent.FieldInputTokens, field.TypeInt64, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(cpausageevent.FieldOutputTokens, field.TypeInt64, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.ReasoningTokens(); ok {
		_spec.SetField(cpausageevent.FieldReasoningTokens, field.TypeInt64, value)
		_node.ReasoningTokens = value
	}
	if value, ok := _c.mutation.CachedTokens(); ok {
		_spec.SetField(cpausageevent.FieldCachedTokens, field.TypeInt64, value)
		_node.CachedTokens = value
	}
	if value, ok := _c.mutation.CacheReadTokens(); ok {
		_spec.SetField(cpausageevent.FieldCacheReadTokens, field.TypeInt64, value)
		_node.CacheReadTokens = value
	}
	if value, ok := _c.mutation.CacheCreationTokens(); ok {
		_spec.SetField(cpausageevent.FieldCacheCreationTokens, field.TypeInt64, value)
		_node.CacheCreationTokens = value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(cpausageevent.FieldTotalTokens, field.TypeInt64, value)
		_node.TotalTokens = value
	}
	if value, ok := _c.mutation.Failed(); ok {
		_spec.SetField(cpausageevent.FieldFailed, field.TypeBool, value)
		_node.Failed = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(cpausageevent.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.RequestedAt(); ok {
		_spec.SetField(cpausageevent.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CpaUsageEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CpaUsageEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CpaUsageEventCreate) OnConflict(opts ...sql.ConflictOption) *CpaUsageEventUpsertOne {
	_c.conflict = opts
	return &CpaUsageEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CpaUsageEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CpaUsageEventCreate) OnConflictColumns(columns ...string) *CpaUsageEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CpaUsageEventUpsertOne{
		create: _c,
	}
}

type (
	// CpaUsageEventUpsertOne is the builder for "upsert"-ing
	//  one CpaUsageEvent node.
	CpaUsageEventUpsertOne struct {
		create *CpaUsageEventCreate
	}

	// CpaUsageEventUpsert is the "OnConflict" setter.
	CpaUsageEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CpaUsageEventUpsert) SetUpdatedAt(v time.Time) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateUpdatedAt() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldUpdatedAt)
	return u
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (u *CpaUsageEventUpsert) SetCpaInstanceID(v int) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldCpaInstanceID, v)
	return u
}

// UpdateCpaInstanceID sets the "cpa_instance_id" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateCpaInstanceID() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldCpaInstanceID)
	return u
}

// AddCpaInstanceID adds v to the "cpa_instance_id" field.
func (u *CpaUsageEventUpsert) AddCpaInstanceID(v int) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldCpaInstanceID, v)
	return u
}

// SetAuthIndex sets the "auth_index" field.
func (u *CpaUsageEventUpsert) SetAuthIndex(v string) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldAuthIndex, v)
	return u
}

// UpdateAuthIndex sets the "auth_index" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateAuthIndex() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldAuthIndex)
	return u
}

// SetProvider sets the "provider" field.
func (u *CpaUsageEventUpsert) SetProvider(v string) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateProvider() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldProvider)
	return u
}

// SetModel sets the "model" field.
func (u *CpaUsageEventUpsert) SetModel(v string) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateModel() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldModel)
	return u
}

// SetSource sets the "source" field.
func (u *CpaUsageEventUpsert) SetSource(v string) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateSource() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldSource)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *CpaUsageEventUpsert) SetInputTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateInputTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *CpaUsageEventUpsert) AddInputTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *CpaUsageEventUpsert) SetOutputTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateOutputTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *CpaUsageEventUpsert) AddOutputTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldOutputTokens, v)
	return u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (u *CpaUsageEventUpsert) SetReasoningTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldReasoningTokens, v)
	return u
}

// UpdateReasoningTokens sets the "reasoning_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateReasoningTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldReasoningTokens)
	return u
}

// AddReasoningTokens adds v to the "reasoning_tokens" field.
func (u *CpaUsageEventUpsert) AddReasoningTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldReasoningTokens, v)
	return u
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *CpaUsageEventUpsert) SetCachedTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldCachedTokens, v)
	return u
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateCachedTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldCachedTokens)
	return u
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *CpaUsageEventUpsert) AddCachedTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldCachedTokens, v)
	return u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *CpaUsageEventUpsert) SetCacheReadTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldCacheReadTokens, v)
	return u
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateCacheReadTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldCacheReadTokens)
	return u
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *CpaUsageEventUpsert) AddCacheReadTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldCacheReadTokens, v)
	return u
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *CpaUsageEventUpsert) SetCacheCreationTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldCacheCreationTokens, v)
	return u
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateCacheCreationTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldCacheCreationTokens)
	return u
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *CpaUsageEventUpsert) AddCacheCreationTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldCacheCreationTokens, v)
	return u
}

// SetTotalTokens sets the "total_tokens" field.
func (u *CpaUsageEventUpsert) SetTotalTokens(v int64) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldTotalTokens, v)
	return u
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateTotalTokens() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldTotalTokens)
	return u
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *CpaUsageEventUpsert) AddTotalTokens(v int64) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldTotalTokens, v)
	return u
}

// SetFailed sets the "failed" field.
func (u *CpaUsageEventUpsert) SetFailed(v bool) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldFailed, v)
	return u
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateFailed() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldFailed)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *CpaUsageEventUpsert) SetStatusCode(v int) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateStatusCode() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *CpaUsageEventUpsert) AddStatusCode(v int) *CpaUsageEventUpsert {
	u.Add(cpausageevent.FieldStatusCode, v)
	return u
}

// SetRequestedAt sets the "requested_at" field.
func (u *CpaUsageEventUpsert) SetRequestedAt(v time.Time) *CpaUsageEventUpsert {
	u.Set(cpausageevent.FieldRequestedAt, v)
	return u
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *CpaUsageEventUpsert) UpdateRequestedAt() *CpaUsageEventUpsert {
	u.SetExcluded(cpausageevent.FieldRequestedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CpaUsageEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CpaUsageEventUpsertOne) UpdateNewValues() *CpaUsageEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cpausageevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CpaUsageEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CpaUsageEventUpsertOne) Ignore() *CpaUsageEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CpaUsageEventUpsertOne) DoNothing() *CpaUsageEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CpaUsageEventCreate.OnConflict
// documentation for more info.
func (u *CpaUsageEventUpsertOne) Update(set func(*CpaUsageEventUpsert)) *CpaUsageEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CpaUsageEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CpaUsageEventUpsertOne) SetUpdatedAt(v time.Time) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateUpdatedAt() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (u *CpaUsageEventUpsertOne) SetCpaInstanceID(v int) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCpaInstanceID(v)
	})
}

// AddCpaInstanceID adds v to the "cpa_instance_id" field.
func (u *CpaUsageEventUpsertOne) AddCpaInstanceID(v int) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCpaInstanceID(v)
	})
}

// UpdateCpaInstanceID sets the "cpa_instance_id" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateCpaInstanceID() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCpaInstanceID()
	})
}

// SetAuthIndex sets the "auth_index" field.
func (u *CpaUsageEventUpsertOne) SetAuthIndex(v string) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetAuthIndex(v)
	})
}

// UpdateAuthIndex sets the "auth_index" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateAuthIndex() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateAuthIndex()
	})
}

// SetProvider sets the "provider" field.
func (u *CpaUsageEventUpsertOne) SetProvider(v string) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateProvider() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *CpaUsageEventUpsertOne) SetModel(v string) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateModel() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateModel()
	})
}

// SetSource sets the "source" field.
func (u *CpaUsageEventUpsertOne) SetSource(v string) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateSource() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateSource()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *CpaUsageEventUpsertOne) SetInputTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *CpaUsageEventUpsertOne) AddInputTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateInputTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *CpaUsageEventUpsertOne) SetOutputTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *CpaUsageEventUpsertOne) AddOutputTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateOutputTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (u *CpaUsageEventUpsertOne) SetReasoningTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetReasoningTokens(v)
	})
}

// AddReasoningTokens adds v to the "reasoning_tokens" field.
func (u *CpaUsageEventUpsertOne) AddReasoningTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddReasoningTokens(v)
	})
}

// UpdateReasoningTokens sets the "reasoning_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateReasoningTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateReasoningTokens()
	})
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *CpaUsageEventUpsertOne) SetCachedTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCachedTokens(v)
	})
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *CpaUsageEventUpsertOne) AddCachedTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCachedTokens(v)
	})
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateCachedTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCachedTokens()
	})
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *CpaUsageEventUpsertOne) SetCacheReadTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCacheReadTokens(v)
	})
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *CpaUsageEventUpsertOne) AddCacheReadTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCacheReadTokens(v)
	})
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateCacheReadTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCacheReadTokens()
	})
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *CpaUsageEventUpsertOne) SetCacheCreationTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCacheCreationTokens(v)
	})
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *CpaUsageEventUpsertOne) AddCacheCreationTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCacheCreationTokens(v)
	})
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateCacheCreationTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCacheCreationTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *CpaUsageEventUpsertOne) SetTotalTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *CpaUsageEventUpsertOne) AddTotalTokens(v int64) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateTotalTokens() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetFailed sets the "failed" field.
func (u *CpaUsageEventUpsertOne) SetFailed(v bool) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetFailed(v)
	})
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateFailed() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateFailed()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *CpaUsageEventUpsertOne) SetStatusCode(v int) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *CpaUsageEventUpsertOne) AddStatusCode(v int) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateStatusCode() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateStatusCode()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *CpaUsageEventUpsertOne) SetRequestedAt(v time.Time) *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *CpaUsageEventUpsertOne) UpdateRequestedAt() *CpaUsageEventUpsertOne {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateRequestedAt()
	})
}

// Exec executes the query.
func (u *CpaUsageEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CpaUsageEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CpaUsageEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CpaUsageEventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CpaUsageEventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CpaUsageEventCreateBulk is the builder for creating many CpaUsageEvent entities in bulk.
type CpaUsageEventCreateBulk struct {
	config
	err      error
	builders []*CpaUsageEventCreate
	conflict []sql.ConflictOption
}

// Save creates the CpaUsageEvent entities in the database.
func (_c *CpaUsageEventCreateBulk) Save(ctx context.Context) ([]*CpaUsageEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CpaUsageEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CpaUsageEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CpaUsageEventCreateBulk) SaveX(ctx context.Context) []*CpaUsageEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CpaUsageEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CpaUsageEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CpaUsageEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CpaUsageEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CpaUsageEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *CpaUsageEventUpsertBulk {
	_c.conflict = opts
	return &CpaUsageEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CpaUsageEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CpaUsageEventCreateBulk) OnConflictColumns(columns ...string) *CpaUsageEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CpaUsageEventUpsertBulk{
		create: _c,
	}
}

// CpaUsageEventUpsertBulk is the builder for "upsert"-ing
// a bulk of CpaUsageEvent nodes.
type CpaUsageEventUpsertBulk struct {
	create *CpaUsageEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CpaUsageEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CpaUsageEventUpsertBulk) UpdateNewValues() *CpaUsageEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cpausageevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CpaUsageEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CpaUsageEventUpsertBulk) Ignore() *CpaUsageEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CpaUsageEventUpsertBulk) DoNothing() *CpaUsageEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CpaUsageEventCreateBulk.OnConflict
// documentation for more info.
func (u *CpaUsageEventUpsertBulk) Update(set func(*CpaUsageEventUpsert)) *CpaUsageEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CpaUsageEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CpaUsageEventUpsertBulk) SetUpdatedAt(v time.Time) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateUpdatedAt() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCpaInstanceID sets the "cpa_instance_id" field.
func (u *CpaUsageEventUpsertBulk) SetCpaInstanceID(v int) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCpaInstanceID(v)
	})
}

// AddCpaInstanceID adds v to the "cpa_instance_id" field.
func (u *CpaUsageEventUpsertBulk) AddCpaInstanceID(v int) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCpaInstanceID(v)
	})
}

// UpdateCpaInstanceID sets the "cpa_instance_id" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateCpaInstanceID() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCpaInstanceID()
	})
}

// SetAuthIndex sets the "auth_index" field.
func (u *CpaUsageEventUpsertBulk) SetAuthIndex(v string) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetAuthIndex(v)
	})
}

// UpdateAuthIndex sets the "auth_index" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateAuthIndex() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateAuthIndex()
	})
}

// SetProvider sets the "provider" field.
func (u *CpaUsageEventUpsertBulk) SetProvider(v string) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateProvider() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateProvider()
	})
}

// SetModel sets the "model" field.
func (u *CpaUsageEventUpsertBulk) SetModel(v string) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateModel() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateModel()
	})
}

// SetSource sets the "source" field.
func (u *CpaUsageEventUpsertBulk) SetSource(v string) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateSource() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateSource()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetInputTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddInputTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateInputTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetOutputTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddOutputTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateOutputTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetReasoningTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetReasoningTokens(v)
	})
}

// AddReasoningTokens adds v to the "reasoning_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddReasoningTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddReasoningTokens(v)
	})
}

// UpdateReasoningTokens sets the "reasoning_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateReasoningTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateReasoningTokens()
	})
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetCachedTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCachedTokens(v)
	})
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddCachedTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCachedTokens(v)
	})
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateCachedTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCachedTokens()
	})
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetCacheReadTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCacheReadTokens(v)
	})
}

// AddCacheReadTokens adds v to the "cache_read_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddCacheReadTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCacheReadTokens(v)
	})
}

// UpdateCacheReadTokens sets the "cache_read_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateCacheReadTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCacheReadTokens()
	})
}

// SetCacheCreationTokens sets the "cache_creation_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetCacheCreationTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetCacheCreationTokens(v)
	})
}

// AddCacheCreationTokens adds v to the "cache_creation_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddCacheCreationTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddCacheCreationTokens(v)
	})
}

// UpdateCacheCreationTokens sets the "cache_creation_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateCacheCreationTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateCacheCreationTokens()
	})
}

// SetTotalTokens sets the "total_tokens" field.
func (u *CpaUsageEventUpsertBulk) SetTotalTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetTotalTokens(v)
	})
}

// AddTotalTokens adds v to the "total_tokens" field.
func (u *CpaUsageEventUpsertBulk) AddTotalTokens(v int64) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddTotalTokens(v)
	})
}

// UpdateTotalTokens sets the "total_tokens" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateTotalTokens() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateTotalTokens()
	})
}

// SetFailed sets the "failed" field.
func (u *CpaUsageEventUpsertBulk) SetFailed(v bool) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetFailed(v)
	})
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateFailed() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateFailed()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *CpaUsageEventUpsertBulk) SetStatusCode(v int) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *CpaUsageEventUpsertBulk) AddStatusCode(v int) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateStatusCode() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateStatusCode()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *CpaUsageEventUpsertBulk) SetRequestedAt(v time.Time) *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *CpaUsageEventUpsertBulk) UpdateRequestedAt() *CpaUsageEventUpsertBulk {
	return u.Update(func(s *CpaUsageEventUpsert) {
		s.UpdateRequestedAt()
	})
}

// Exec executes the query.
func (u *CpaUsageEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CpaUsageEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CpaUsageEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CpaUsageEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
