// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/cpausageevent"
)

// CpaUsageEvent is the model entity for the CpaUsageEvent schema.
type CpaUsageEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CpaInstanceID holds the value of the "cpa_instance_id" field.
	CpaInstanceID int `json:"cpa_instance_id,omitempty"`
	// AuthIndex holds the value of the "auth_index" field.
	AuthIndex string `json:"auth_index,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int64 `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int64 `json:"output_tokens,omitempty"`
	// ReasoningTokens holds the value of the "reasoning_tokens" field.
	ReasoningTokens int64 `json:"reasoning_tokens,omitempty"`
	// CachedTokens holds the value of the "cached_tokens" field.
	CachedTokens int64 `json:"cached_tokens,omitempty"`
	// CacheReadTokens holds the value of the "cache_read_tokens" field.
	CacheReadTokens int64 `json:"cache_read_tokens,omitempty"`
	// CacheCreationTokens holds the value of the "cache_creation_tokens" field.
	CacheCreationTokens int64 `json:"cache_creation_tokens,omitempty"`
	// TotalTokens holds the value of the "total_tokens" field.
	TotalTokens int64 `json:"total_tokens,omitempty"`
	// Failed holds the value of the "failed" field.
	Failed bool `json:"failed,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode int `json:"status_code,omitempty"`
	// RequestedAt holds the value of the "requested_at" field.
	RequestedAt  time.Time `json:"requested_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CpaUsageEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cpausageevent.FieldFailed:
			values[i] = new(sql.NullBool)
		case cpausageevent.FieldID, cpausageevent.FieldCpaInstanceID, cpausageevent.FieldInputTokens, cpausageevent.FieldOutputTokens, cpausageevent.FieldReasoningTokens, cpausageevent.FieldCachedTokens, cpausageevent.FieldCacheReadTokens, cpausageevent.FieldCacheCreationTokens, cpausageevent.FieldTotalTokens, cpausageevent.FieldStatusCode:
			values[i] = new(sql.NullInt64)
		case cpausageevent.FieldAuthIndex, cpausageevent.FieldProvider, cpausageevent.FieldModel, cpausageevent.FieldSource:
			values[i] = new(sql.NullString)
		case cpausageevent.FieldCreatedAt, cpausageevent.FieldUpdatedAt, cpausageevent.FieldRequestedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CpaUsageEvent fields.
func (_m *CpaUsageEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cpausageevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cpausageevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cpausageevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cpausageevent.FieldCpaInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cpa_instance_id", values[i])
			} else if value.Valid {
				_m.CpaInstanceID = int(value.Int64)
			}
		case cpausageevent.FieldAuthIndex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_index", values[i])
			} else if value.Valid {
				_m.AuthIndex = value.String
			}
		case cpausageevent.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case cpausageevent.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case cpausageevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case cpausageevent.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = value.Int64
			}
		case cpausageevent.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = value.Int64
			}
		case cpausageevent.FieldReasoningTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reasoning_tokens", values[i])
			} else if value.Valid {
				_m.ReasoningTokens = value.Int64
			}
		case cpausageevent.FieldCachedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_tokens", values[i])
			} else if value.Valid {
				_m.CachedTokens = value.Int64
			}
		case cpausageevent.FieldCacheReadTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_tokens", values[i])
			} else if value.Valid {
				_m.CacheReadTokens = value.Int64
			}
		case cpausageevent.FieldCacheCreationTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_creation_tokens", values[i])
			} else if value.Valid {
				_m.CacheCreationTokens = value.Int64
			}
		case cpausageevent.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = value.Int64
			}
		case cpausageevent.FieldFailed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field failed", values[i])
			} else if value.Valid {
				_m.Failed = value.Bool
			}
		case cpausageevent.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				_m.StatusCode = int(value.Int64)
			}
		case cpausageevent.FieldRequestedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field requested_at", values[i])
			} else if value.Valid {
				_m.RequestedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CpaUsageEvent.
// This includes values selected through modifiers, order, etc.
func (_m *CpaUsageEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CpaUsageEvent.
// Note that you need to call CpaUsageEvent.Unwrap() before calling this method if this CpaUsageEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CpaUsageEvent) Update() *CpaUsageEventUpdateOne {
	return NewCpaUsageEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CpaUsageEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CpaUsageEvent) Unwrap() *CpaUsageEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CpaUsageEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CpaUsageEvent) String() string {
	var builder strings.Builder
	builder.WriteString("CpaUsageEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("cpa_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CpaInstanceID))
	builder.WriteString(", ")
	builder.WriteString("auth_index=")
	builder.WriteString(_m.AuthIndex)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("reasoning_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReasoningTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_read_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_creation_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheCreationTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("failed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Failed))
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("requested_at=")
	builder.WriteString(_m.RequestedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CpaUsageEvents is a parsable slice of CpaUsageEvent.
type CpaUsageEvents []*CpaUsageEvent
