// Code generated by ent, DO NOT EDIT.

package cparesetattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreditKey applies equality check predicate on the "credit_key" field. It's identical to CreditKeyEQ.
func CreditKey(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldCreditKey, v))
}

// CredentialID applies equality check predicate on the "credential_id" field. It's identical to CredentialIDEQ.
func CredentialID(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldCredentialID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldRequestID, v))
}

// GrantID applies equality check predicate on the "grant_id" field. It's identical to GrantIDEQ.
func GrantID(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldGrantID, v))
}

// ResetsLeft applies equality check predicate on the "resets_left" field. It's identical to ResetsLeftEQ.
func ResetsLeft(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldResetsLeft, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v Provider) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v Provider) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...Provider) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...Provider) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldProvider, vs...))
}

// CreditKeyEQ applies the EQ predicate on the "credit_key" field.
func CreditKeyEQ(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldCreditKey, v))
}

// CreditKeyNEQ applies the NEQ predicate on the "credit_key" field.
func CreditKeyNEQ(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldCreditKey, v))
}

// CreditKeyIn applies the In predicate on the "credit_key" field.
func CreditKeyIn(vs ...string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldCreditKey, vs...))
}

// CreditKeyNotIn applies the NotIn predicate on the "credit_key" field.
func CreditKeyNotIn(vs ...string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldCreditKey, vs...))
}

// CreditKeyGT applies the GT predicate on the "credit_key" field.
func CreditKeyGT(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldCreditKey, v))
}

// CreditKeyGTE applies the GTE predicate on the "credit_key" field.
func CreditKeyGTE(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldCreditKey, v))
}

// CreditKeyLT applies the LT predicate on the "credit_key" field.
func CreditKeyLT(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldCreditKey, v))
}

// CreditKeyLTE applies the LTE predicate on the "credit_key" field.
func CreditKeyLTE(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldCreditKey, v))
}

// CreditKeyContains applies the Contains predicate on the "credit_key" field.
func CreditKeyContains(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldContains(FieldCreditKey, v))
}

// CreditKeyHasPrefix applies the HasPrefix predicate on the "credit_key" field.
func CreditKeyHasPrefix(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldHasPrefix(FieldCreditKey, v))
}

// CreditKeyHasSuffix applies the HasSuffix predicate on the "credit_key" field.
func CreditKeyHasSuffix(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldHasSuffix(FieldCreditKey, v))
}

// CreditKeyEqualFold applies the EqualFold predicate on the "credit_key" field.
func CreditKeyEqualFold(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEqualFold(FieldCreditKey, v))
}

// CreditKeyContainsFold applies the ContainsFold predicate on the "credit_key" field.
func CreditKeyContainsFold(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldContainsFold(FieldCreditKey, v))
}

// CredentialIDEQ applies the EQ predicate on the "credential_id" field.
func CredentialIDEQ(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldCredentialID, v))
}

// CredentialIDNEQ applies the NEQ predicate on the "credential_id" field.
func CredentialIDNEQ(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldCredentialID, v))
}

// CredentialIDIn applies the In predicate on the "credential_id" field.
func CredentialIDIn(vs ...int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldCredentialID, vs...))
}

// CredentialIDNotIn applies the NotIn predicate on the "credential_id" field.
func CredentialIDNotIn(vs ...int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldCredentialID, vs...))
}

// CredentialIDGT applies the GT predicate on the "credential_id" field.
func CredentialIDGT(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldCredentialID, v))
}

// CredentialIDGTE applies the GTE predicate on the "credential_id" field.
func CredentialIDGTE(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldCredentialID, v))
}

// CredentialIDLT applies the LT predicate on the "credential_id" field.
func CredentialIDLT(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldCredentialID, v))
}

// CredentialIDLTE applies the LTE predicate on the "credential_id" field.
func CredentialIDLTE(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldCredentialID, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldState, vs...))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldContainsFold(FieldRequestID, v))
}

// GrantIDEQ applies the EQ predicate on the "grant_id" field.
func GrantIDEQ(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldGrantID, v))
}

// GrantIDNEQ applies the NEQ predicate on the "grant_id" field.
func GrantIDNEQ(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldGrantID, v))
}

// GrantIDIn applies the In predicate on the "grant_id" field.
func GrantIDIn(vs ...string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldGrantID, vs...))
}

// GrantIDNotIn applies the NotIn predicate on the "grant_id" field.
func GrantIDNotIn(vs ...string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldGrantID, vs...))
}

// GrantIDGT applies the GT predicate on the "grant_id" field.
func GrantIDGT(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldGrantID, v))
}

// GrantIDGTE applies the GTE predicate on the "grant_id" field.
func GrantIDGTE(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldGrantID, v))
}

// GrantIDLT applies the LT predicate on the "grant_id" field.
func GrantIDLT(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldGrantID, v))
}

// GrantIDLTE applies the LTE predicate on the "grant_id" field.
func GrantIDLTE(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldGrantID, v))
}

// GrantIDContains applies the Contains predicate on the "grant_id" field.
func GrantIDContains(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldContains(FieldGrantID, v))
}

// GrantIDHasPrefix applies the HasPrefix predicate on the "grant_id" field.
func GrantIDHasPrefix(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldHasPrefix(FieldGrantID, v))
}

// GrantIDHasSuffix applies the HasSuffix predicate on the "grant_id" field.
func GrantIDHasSuffix(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldHasSuffix(FieldGrantID, v))
}

// GrantIDEqualFold applies the EqualFold predicate on the "grant_id" field.
func GrantIDEqualFold(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEqualFold(FieldGrantID, v))
}

// GrantIDContainsFold applies the ContainsFold predicate on the "grant_id" field.
func GrantIDContainsFold(v string) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldContainsFold(FieldGrantID, v))
}

// ResetsLeftEQ applies the EQ predicate on the "resets_left" field.
func ResetsLeftEQ(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldEQ(FieldResetsLeft, v))
}

// ResetsLeftNEQ applies the NEQ predicate on the "resets_left" field.
func ResetsLeftNEQ(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNEQ(FieldResetsLeft, v))
}

// ResetsLeftIn applies the In predicate on the "resets_left" field.
func ResetsLeftIn(vs ...int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIn(FieldResetsLeft, vs...))
}

// ResetsLeftNotIn applies the NotIn predicate on the "resets_left" field.
func ResetsLeftNotIn(vs ...int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotIn(FieldResetsLeft, vs...))
}

// ResetsLeftGT applies the GT predicate on the "resets_left" field.
func ResetsLeftGT(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGT(FieldResetsLeft, v))
}

// ResetsLeftGTE applies the GTE predicate on the "resets_left" field.
func ResetsLeftGTE(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldGTE(FieldResetsLeft, v))
}

// ResetsLeftLT applies the LT predicate on the "resets_left" field.
func ResetsLeftLT(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLT(FieldResetsLeft, v))
}

// ResetsLeftLTE applies the LTE predicate on the "resets_left" field.
func ResetsLeftLTE(v int) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldLTE(FieldResetsLeft, v))
}

// ResetsLeftIsNil applies the IsNil predicate on the "resets_left" field.
func ResetsLeftIsNil() predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldIsNull(FieldResetsLeft))
}

// ResetsLeftNotNil applies the NotNil predicate on the "resets_left" field.
func ResetsLeftNotNil() predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.FieldNotNull(FieldResetsLeft))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CPAResetAttempt) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CPAResetAttempt) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CPAResetAttempt) predicate.CPAResetAttempt {
	return predicate.CPAResetAttempt(sql.NotPredicates(p))
}
