// Code generated by ent, DO NOT EDIT.

package cpausageevent

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cpausageevent type in the database.
	Label = "cpa_usage_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCpaInstanceID holds the string denoting the cpa_instance_id field in the database.
	FieldCpaInstanceID = "cpa_instance_id"
	// FieldAuthIndex holds the string denoting the auth_index field in the database.
	FieldAuthIndex = "auth_index"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldReasoningTokens holds the string denoting the reasoning_tokens field in the database.
	FieldReasoningTokens = "reasoning_tokens"
	// FieldCachedTokens holds the string denoting the cached_tokens field in the database.
	FieldCachedTokens = "cached_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldCacheCreationTokens holds the string denoting the cache_creation_tokens field in the database.
	FieldCacheCreationTokens = "cache_creation_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldFailed holds the string denoting the failed field in the database.
	FieldFailed = "failed"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldRequestedAt holds the string denoting the requested_at field in the database.
	FieldRequestedAt = "requested_at"
	// Table holds the table name of the cpausageevent in the database.
	Table = "cpa_usage_events"
)

// Columns holds all SQL columns for cpausageevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCpaInstanceID,
	FieldAuthIndex,
	FieldProvider,
	FieldModel,
	FieldSource,
	FieldInputTokens,
	FieldOutputTokens,
	FieldReasoningTokens,
	FieldCachedTokens,
	FieldCacheReadTokens,
	FieldCacheCreationTokens,
	FieldTotalTokens,
	FieldFailed,
	FieldStatusCode,
	FieldRequestedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAuthIndex holds the default value on creation for the "auth_index" field.
	DefaultAuthIndex string
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultReasoningTokens holds the default value on creation for the "reasoning_tokens" field.
	DefaultReasoningTokens int64
	// DefaultCachedTokens holds the default value on creation for the "cached_tokens" field.
	DefaultCachedTokens int64
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int64
	// DefaultCacheCreationTokens holds the default value on creation for the "cache_creation_tokens" field.
	DefaultCacheCreationTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultFailed holds the default value on creation for the "failed" field.
	DefaultFailed bool
	// DefaultStatusCode holds the default value on creation for the "status_code" field.
	DefaultStatusCode int
)

// OrderOption defines the ordering options for the CpaUsageEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCpaInstanceID orders the results by the cpa_instance_id field.
func ByCpaInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCpaInstanceID, opts...).ToFunc()
}

// ByAuthIndex orders the results by the auth_index field.
func ByAuthIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthIndex, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByReasoningTokens orders the results by the reasoning_tokens field.
func ByReasoningTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasoningTokens, opts...).ToFunc()
}

// ByCachedTokens orders the results by the cached_tokens field.
func ByCachedTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByCacheCreationTokens orders the results by the cache_creation_tokens field.
func ByCacheCreationTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheCreationTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByFailed orders the results by the failed field.
func ByFailed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailed, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByRequestedAt orders the results by the requested_at field.
func ByRequestedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedAt, opts...).ToFunc()
}
