package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"

	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/looplj/axonhub/internal/server/biz"
)

// QuotaState is the resolver for the quotaState field.
func (r *cPAManagedCredentialResolver) QuotaState(ctx context.Context, obj *biz.CPACredentialView) (objects.CPAQuotaState, error) {
	return objects.CPAQuotaState(obj.QuotaState), nil
}

// CreateCPAInstance is the resolver for the createCPAInstance field.
func (r *mutationResolver) CreateCPAInstance(ctx context.Context, input biz.CreateCPAInstanceInput) (*biz.CPAInstanceView, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return nil, fmt.Errorf("permission denied: requires write:settings scope")
	}
	return r.cpaService.CreateInstance(ctx, input)
}

// UpdateCPAInstance is the resolver for the updateCPAInstance field.
func (r *mutationResolver) UpdateCPAInstance(ctx context.Context, id int, input biz.UpdateCPAInstanceInput) (*biz.CPAInstanceView, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return nil, fmt.Errorf("permission denied: requires write:settings scope")
	}
	return r.cpaService.UpdateInstance(ctx, id, input)
}

// DeleteCPAInstance is the resolver for the deleteCPAInstance field.
func (r *mutationResolver) DeleteCPAInstance(ctx context.Context, id int) (bool, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return false, fmt.Errorf("permission denied: requires write:settings scope")
	}
	if err := r.cpaService.DeleteInstance(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RefreshCPAInstance is the resolver for the refreshCPAInstance field.
func (r *mutationResolver) RefreshCPAInstance(ctx context.Context, instanceID int, provider *string) (*biz.CPARefreshResult, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return nil, fmt.Errorf("permission denied: requires write:settings scope")
	}
	return r.cpaService.RefreshInstance(ctx, instanceID, provider)
}

// RefreshCPACredential is the resolver for the refreshCPACredential field.
func (r *mutationResolver) RefreshCPACredential(ctx context.Context, credentialID int) (*biz.CPACredentialView, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return nil, fmt.Errorf("permission denied: requires write:settings scope")
	}
	return r.cpaService.RefreshCredential(ctx, credentialID)
}

// ToggleCPACredential is the resolver for the toggleCPACredential field.
func (r *mutationResolver) ToggleCPACredential(ctx context.Context, credentialID int, disabled bool) (*biz.CPACredentialView, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return nil, fmt.Errorf("permission denied: requires write:settings scope")
	}
	return r.cpaService.ToggleCredential(ctx, credentialID, disabled)
}

// ResetCPACodexCredential is the resolver for the resetCPACodexCredential field.
func (r *mutationResolver) ResetCPACodexCredential(ctx context.Context, credentialID int, creditID string) (bool, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeWriteSettings) {
		return false, fmt.Errorf("permission denied: requires write:settings scope")
	}
	return r.cpaService.ResetCodexCredential(ctx, credentialID, creditID)
}

// CpaInstances is the resolver for the cpaInstances field.
func (r *queryResolver) CpaInstances(ctx context.Context) ([]*biz.CPAInstanceView, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeReadSettings) {
		return nil, fmt.Errorf("permission denied: requires read:settings scope")
	}
	return r.cpaService.ListInstances(ctx)
}

// CpaInstance is the resolver for the cpaInstance field.
func (r *queryResolver) CpaInstance(ctx context.Context, id int) (*biz.CPAInstanceView, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeReadSettings) {
		return nil, fmt.Errorf("permission denied: requires read:settings scope")
	}
	return r.cpaService.GetInstance(ctx, id)
}

// QueryCPACredentials is the resolver for the queryCPACredentials field.
func (r *queryResolver) QueryCPACredentials(ctx context.Context, input biz.QueryCPACredentialsInput) (*biz.CPACredentialConnection, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeReadSettings) {
		return nil, fmt.Errorf("permission denied: requires read:settings scope")
	}
	return r.cpaService.QueryCredentials(ctx, input)
}

// CpaOverview is the resolver for the cpaOverview field.
func (r *queryResolver) CpaOverview(ctx context.Context, instanceID int) (*biz.CPAOverview, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeReadSettings) {
		return nil, fmt.Errorf("permission denied: requires read:settings scope")
	}
	return r.cpaService.Overview(ctx, instanceID)
}

// CpaRefreshProgress is the resolver for the cpaRefreshProgress field.
func (r *queryResolver) CpaRefreshProgress(ctx context.Context, instanceID int) (*biz.CPARefreshProgress, error) {
	if !scopes.UserHasScope(ctx, scopes.ScopeReadSettings) {
		return nil, fmt.Errorf("permission denied: requires read:settings scope")
	}
	progress, _ := r.cpaService.RefreshProgress(instanceID)
	return progress, nil
}

// CPAManagedCredential returns CPAManagedCredentialResolver implementation.
func (r *Resolver) CPAManagedCredential() CPAManagedCredentialResolver {
	return &cPAManagedCredentialResolver{r}
}

type cPAManagedCredentialResolver struct{ *Resolver }
