// Code generated by ent, DO NOT EDIT.

package cpainstance

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the cpainstance type in the database.
	Label = "cpa_instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldEncryptedSecret holds the string denoting the encrypted_secret field in the database.
	FieldEncryptedSecret = "encrypted_secret"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldInsecureSkipTLS holds the string denoting the insecure_skip_tls field in the database.
	FieldInsecureSkipTLS = "insecure_skip_tls"
	// FieldAutoRefreshEnabled holds the string denoting the auto_refresh_enabled field in the database.
	FieldAutoRefreshEnabled = "auto_refresh_enabled"
	// FieldRefreshIntervalMinutes holds the string denoting the refresh_interval_minutes field in the database.
	FieldRefreshIntervalMinutes = "refresh_interval_minutes"
	// FieldNextRefreshAt holds the string denoting the next_refresh_at field in the database.
	FieldNextRefreshAt = "next_refresh_at"
	// FieldServerVersion holds the string denoting the server_version field in the database.
	FieldServerVersion = "server_version"
	// FieldServerCommit holds the string denoting the server_commit field in the database.
	FieldServerCommit = "server_commit"
	// FieldServerBuildDate holds the string denoting the server_build_date field in the database.
	FieldServerBuildDate = "server_build_date"
	// FieldLastSyncAttemptAt holds the string denoting the last_sync_attempt_at field in the database.
	FieldLastSyncAttemptAt = "last_sync_attempt_at"
	// FieldLastSyncSuccessAt holds the string denoting the last_sync_success_at field in the database.
	FieldLastSyncSuccessAt = "last_sync_success_at"
	// FieldLastErrorAt holds the string denoting the last_error_at field in the database.
	FieldLastErrorAt = "last_error_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// EdgeCredentials holds the string denoting the credentials edge name in mutations.
	EdgeCredentials = "credentials"
	// Table holds the table name of the cpainstance in the database.
	Table = "cpa_instances"
	// CredentialsTable is the table that holds the credentials relation/edge.
	CredentialsTable = "cpa_credentials"
	// CredentialsInverseTable is the table name for the CPACredential entity.
	// It exists in this package in order to avoid circular dependency with the "cpacredential" package.
	CredentialsInverseTable = "cpa_credentials"
	// CredentialsColumn is the table column denoting the credentials relation/edge.
	CredentialsColumn = "cpa_instance_id"
)

// Columns holds all SQL columns for cpainstance fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldBaseURL,
	FieldEncryptedSecret,
	FieldEnabled,
	FieldInsecureSkipTLS,
	FieldAutoRefreshEnabled,
	FieldRefreshIntervalMinutes,
	FieldNextRefreshAt,
	FieldServerVersion,
	FieldServerCommit,
	FieldServerBuildDate,
	FieldLastSyncAttemptAt,
	FieldLastSyncSuccessAt,
	FieldLastErrorAt,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultInsecureSkipTLS holds the default value on creation for the "insecure_skip_tls" field.
	DefaultInsecureSkipTLS bool
	// DefaultAutoRefreshEnabled holds the default value on creation for the "auto_refresh_enabled" field.
	DefaultAutoRefreshEnabled bool
	// DefaultRefreshIntervalMinutes holds the default value on creation for the "refresh_interval_minutes" field.
	DefaultRefreshIntervalMinutes int
	// RefreshIntervalMinutesValidator is a validator for the "refresh_interval_minutes" field. It is called by the builders before save.
	RefreshIntervalMinutesValidator func(int) error
	// DefaultServerVersion holds the default value on creation for the "server_version" field.
	DefaultServerVersion string
	// DefaultServerCommit holds the default value on creation for the "server_commit" field.
	DefaultServerCommit string
	// DefaultServerBuildDate holds the default value on creation for the "server_build_date" field.
	DefaultServerBuildDate string
)

// OrderOption defines the ordering options for the CPAInstance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByEncryptedSecret orders the results by the encrypted_secret field.
func ByEncryptedSecret(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedSecret, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByInsecureSkipTLS orders the results by the insecure_skip_tls field.
func ByInsecureSkipTLS(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInsecureSkipTLS, opts...).ToFunc()
}

// ByAutoRefreshEnabled orders the results by the auto_refresh_enabled field.
func ByAutoRefreshEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoRefreshEnabled, opts...).ToFunc()
}

// ByRefreshIntervalMinutes orders the results by the refresh_interval_minutes field.
func ByRefreshIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshIntervalMinutes, opts...).ToFunc()
}

// ByNextRefreshAt orders the results by the next_refresh_at field.
func ByNextRefreshAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRefreshAt, opts...).ToFunc()
}

// ByServerVersion orders the results by the server_version field.
func ByServerVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerVersion, opts...).ToFunc()
}

// ByServerCommit orders the results by the server_commit field.
func ByServerCommit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerCommit, opts...).ToFunc()
}

// ByServerBuildDate orders the results by the server_build_date field.
func ByServerBuildDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerBuildDate, opts...).ToFunc()
}

// ByLastSyncAttemptAt orders the results by the last_sync_attempt_at field.
func ByLastSyncAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAttemptAt, opts...).ToFunc()
}

// ByLastSyncSuccessAt orders the results by the last_sync_success_at field.
func ByLastSyncSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncSuccessAt, opts...).ToFunc()
}

// ByLastErrorAt orders the results by the last_error_at field.
func ByLastErrorAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCredentialsCount orders the results by credentials count.
func ByCredentialsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCredentialsStep(), opts...)
	}
}

// ByCredentials orders the results by credentials terms.
func ByCredentials(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCredentialsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCredentialsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CredentialsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CredentialsTable, CredentialsColumn),
	)
}
